### ISSUE TITLE
UnsatisfiedLinkError

### ISSUE THREAD

**Issue by nguyendinhduc** [bytedeco/javacpp#116] opened 2016-07-25 10:25 UTC
java.lang.UnsatisfiedLinkError: dlopen failed: /data/app/com.qd.videorecorder-1/lib/arm/libavcodec.so: has text relocations
NewFFmpegFrameRecorder.<clinit>(NewFFmpegFrameRecorder.java:182)

**Comment by saudet** [comment] 2016-07-25 11:27
Duplicate of https://github.com/bytedeco/javacv/issues/245

It has been fixed in version 1.2. Please upgrade to version 1.2.

**Closed by saudet** 2016-07-25 11:27 UTC
Labels: bug, duplicate
