### ISSUE TITLE
Leverage foreign linker API as an alternative to JNI 

### ISSUE THREAD

**Issue by LifeIsStrange** [bytedeco/javacpp#453] opened 2021-02-03 17:46 UTC
https://openjdk.java.net/jeps/389
See also
https://inside.java/2020/12/21/podcast-010/
And the official tool jextract 
https://github.com/openjdk/panama-foreign/blob/2d966367a7c9e0cf543ab0cdc159cb3d4ef8f165/doc/panama_jextract.md

Openjdk 16 is meant to be released next month :)

Unrelated but interesting:
https://openjdk.java.net/jeps/338

**Comment by LifeIsStrange** [comment] 2021-02-03 17:47
Cf https://github.com/bytedeco/javacpp/issues/402

**Comment by saudet** [comment] 2021-02-04 00:05
The problem with Panama is that they have no plans to support anything related to C++, and they haven't been able to get any performance gains over JNI, yet, so it's unclear how it's going to be useful at this point. Let's track this as part of issue #51 though.

/cc @mcimadamore

**Comment by saudet** [comment] 2021-02-04 00:06
Duplicate of issue #51

**Closed by saudet** 2021-02-04 00:06 UTC
Labels: duplicate, enhancement

**Comment by mcimadamore** [comment] 2021-02-15 19:14
Sorry for the delay. While it's true that the Foreign Linker API does not support C++ directly (at least not yet), I believe the way in which JavaCPP works is to generate a bunch of "helper" JNI code which then mimics some of the common C++ operations, such as class allocation, etc. If my understanding is correct, this intermediate layer of JNI code doesn't _really_ need to be kept in JNI and could be generated also in some other way (e.g. plain C code which is then linked using the Foreign Linker API). The big issue I see is that the Java _API_ that JavaCPP deals with assumes JNI almost by design - for instance, a class `allocate` method, or its getter/setter methods are Java `native` method, which means this will require some backing JNI stub anyway, so while you're there, I can understand that it makes sense to just stick with JNI for binding to the underlying library as well.

Performance-wise, while the foreign linker does not speed up calls from Java to native, compared with JNI (**), there are some cases in which the new API fares quite well, and that's when native function accept/return parameter by value. In such cases, depending on how return/pass by value is emulated in JNI, the difference with the Foreign Linker API (which supports passing by value natively) can be non-negligible.

(**) in case of back to back native calls, or calls to native code that is very short-lived, the Foreign Linker API supports an invocation mode which avoids Java to native state transitions, which can be useful to reduce latency (but should be used with caution, as it has the potential to crash the VM - e.g. if the function calls back to Java). We are also investigating optimizations for upcalls (e.g. from native back to Java), and we're more confident there that there is more room for improvement (the code to go from Java to native is well optimized in JNI, but the same cannot be said for the other way around).
