### ISSUE TITLE
Audio and Video Out of Sync (Live RTMP)

### ISSUE THREAD

**Issue by wooden1985** [bytedeco/javacpp#131] opened 2016-09-20 06:51 UTC
When I use FFmpegFrameRecorder to push live rtmp stream,In
general, this works very well, and the results look great. However,
unfortunately A/V seems to out of sync after running for  5-6
minutes.

**Comment by saudet** [comment] 2016-09-20 08:10
Make sure to call setTimestamp() before calling record().

**Comment by wooden1985** [comment] 2016-09-21 04:37
I has call setTimestamp

**Comment by saudet** [comment] 2016-09-21 06:13
Ok, could you post that section of code?

BTW, does the same thing happen with the ffmpeg tool on the command line?

And it sounds a lot like a duplicate of either https://github.com/bytedeco/javacv/issues/458 or https://github.com/bytedeco/javacv/issues/128 so let's continue the discussion there. Thanks!

**Closed by saudet** 2016-09-21 06:13 UTC
Labels: duplicate
