### ISSUE TITLE
BytePointer missing static { Loader.load(); } ?

### ISSUE THREAD

**Issue by jo-m** [bytedeco/javacpp#112] opened 2016-07-13 06:52 UTC
I have generated Java linkings for a custom C++ library. Everything is compiled and linked together and packed into a JAR. It generally works fine. However I found that when I use `BytePointer ptr = new BytePointer(byte[]);` without using one of my native classes in Java before, I get an exception:

```
Execution exception[[RuntimeException: No native JavaCPP library in memory. (Has Loader.load() been called?)]]
```

I was able to boil it down to a small case, using OpenCV as example library (which also proves that the problem is not exclusive to my case). The source code is below, the [attached zip](https://github.com/bytedeco/javacpp/files/360855/test-java.zip) contains the same code and also a Makefile. To run, javacpp.jar, opencv.jar and opencv-linux-x86_64.jar are needed.

```
import org.bytedeco.javacpp.*;
import static org.bytedeco.javacpp.opencv_core.Mat;

public class Main {
    public static void works() {
        Mat pano = new Mat();
        byte[] bs = new byte[10];
        BytePointer ptr = new BytePointer(bs);
    }

    public static void broken() {
        byte[] bs = new byte[10];
        BytePointer ptr = new BytePointer(bs);
    }

    public static void main(String[] args) {
        broken();
    }
}
```

**Comment by saudet** [comment] 2016-07-13 10:24
Duplicate of https://github.com/bytedeco/javacpp/issues/44

**Closed by saudet** 2016-07-13 10:24 UTC
Labels: duplicate, question
