### ISSUE TITLE
java.lang.NoClassDefFoundError: Could not initialize class org.bytedeco.javacpp.opencv_features2d$BFMatcher

### ISSUE THREAD

**Issue by chuzhifeng** [bytedeco/javacpp#425] opened 2020-09-21 06:45 UTC
hi, 
i use javacpp 1.4.3 by maven as follow:

`<dependency>
                <groupId>org.bytedeco</groupId>
                <artifactId>javacv</artifactId>
                <version>1.4.3</version>
            </dependency> `

I want to use the SIFT algorithm to extract the features of an image, so when i use class of org.bytedeco.javacpp.opencv_features2d.

when in the MAC environment, it is useful. but When migrating to a CentOS environment, i get a error ：

`java.lang.NoClassDefFoundError: Could not initialize class org.bytedeco.javacpp.opencv_features2d$BFMatcher
	at com.uqun.image.service.impl.GroupImageCheckServiceImpl.siftHandle(GroupImageCheckServiceImpl.java:777)
	at com.uqun.image.service.impl.GroupImageCheckServiceImpl.imageCheck(GroupImageCheckServiceImpl.java:679)
	at com.uqun.image.service.impl.GroupImageCheckServiceImpl.nlpCheckImage(GroupImageCheckServiceImpl.java:526)
	at com.image.service.impl.GroupImageCheckServiceImpl.newGroupImageCheckFeign(GroupImageCheckServiceImpl.java:238)
	at com.uqun.image.web.controller.NewImageController.newGroupImageCheck(NewImageController.java:55)
	at com.uqun.image.web.controller.NewImageController$$FastClassBySpringCGLIB$$241a792c.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)`

could you help me see what's wrong ?

**Comment by saudet** [comment] 2020-09-21 06:48
Try again with the latest version.

**Comment by saudet** [comment] 2020-09-29 21:25
Given the lack of feedback, I'm assuming it's working with the latest version, but if it's not, please make sure that GTK is installed. This is typically what fails to load on Linux, see issue https://github.com/bytedeco/javacpp-presets/issues/593.

**Comment by saudet** [comment] 2020-09-29 21:25
Duplicate of https://github.com/bytedeco/javacv/issues/1490

**Closed by saudet** 2020-09-29 21:25 UTC
Labels: duplicate, question
