### ISSUE TITLE
Javacv Mat to Opencv Mat

### ISSUE THREAD

**Issue by mnh-aj123** [bytedeco/javacpp#178] opened 2017-05-04 09:53 UTC
I am converting Javacv mat to Opencv i am succeeded if i do in this manner .
    ```

        while ((grabbedImage = converter.convert(grabber.grab())) != null) {
           
            Mat imgFrame2 = new Mat(grabbedImage.address());

            Mat imgFrame2Copy = new Mat();
            imgFrame2.copyTo(imgFrame2Copy);


             Imgproc.cvtColor(imgFrame2Copy, imgFrame2Copy, Imgproc.COLOR_BGR2GRAY, 0);

            Imgproc.GaussianBlur(imgFrame2Copy, imgFrame2Copy, new Size(5, 5), 0);
            
            Imgproc.resize(imgFrame2Copy, imgFrame2Copy, new Size(1000,500));
            
            opencv_core.Mat output = new opencv_core.Mat() {
                {
                    address = imgFrame2Copy.getNativeObjAddr();
                }
            };
            
            
            Frame rotatedFrame = converter.convert(output);
            frame.showImage(rotatedFrame);
            
        }
    ```
the above code works fine and there my system doesnot hang
but when i try to Clone()

    ```
        while ((grabbedImage = converter.convert(grabber.grab())) != null) {

            Mat imgFrame2 = new Mat(grabbedImage.address());

            
            Mat imgFrame1Copy=new Mat();
            imgFrame1.copyTo(imgFrame1Copy);
            
            Mat imgFrame2Copy = new Mat();
            imgFrame2.copyTo(imgFrame2Copy);


              Imgproc.cvtColor(imgFrame1Copy, imgFrame1Copy, Imgproc.COLOR_BGR2GRAY, 0);
              Imgproc.cvtColor(imgFrame2Copy, imgFrame2Copy, Imgproc.COLOR_BGR2GRAY, 0);

            Imgproc.GaussianBlur(imgFrame1Copy, imgFrame1Copy, new Size(5, 5), 0);
            Imgproc.GaussianBlur(imgFrame2Copy, imgFrame2Copy, new Size(5, 5), 0);
            
            Imgproc.resize(imgFrame1Copy, imgFrame1Copy, new Size(1000,500));
            Imgproc.resize(imgFrame2Copy, imgFrame2Copy, new Size(1000,500));
            
           Mat imgDifference =new Mat();
           Core.absdiff(imgFrame1Copy, imgFrame2Copy, imgDifference);

            
            opencv_core.Mat output = new opencv_core.Mat() {
                {
                    address = imgDifference.getNativeObjAddr();
                }
            };
            
            
            Frame rotatedFrame = converter.convert(output);
            frame.showImage(rotatedFrame);

            // imgFrame1 = imgFrame2.clone();
            imgFrame2.copyTo(imgFrame1);            
        }
    ```
When i use imgFrame1 any where it  freezes my system . I am unable to understand any one who can solve my  problem ?

I also tried copyTo instead of clone() but still system freezes .
Updated:
```
imgFrame2.copyTo(imgFrame1);
```

**Comment by saudet** [comment] 2017-05-04 10:26
You'll need to initialize imgFrame1 to something if you expect it to do
anything meaningful.

**Comment by mnh-aj123** [comment] 2017-05-04 11:27
@saudet  i initialized it outside the loop with first frame of the video

**Comment by saudet** [comment] 2017-05-04 14:28
That tells me nothing.

**Comment by saudet** [comment] 2017-05-04 14:28
Anyway, marking this as a duplicate of #38.

Please provide more information if you would like to receive more help, thank you!

**Closed by saudet** 2017-05-04 14:28 UTC
Labels: duplicate, question

**Comment by mnh-aj123** [comment] 2017-05-04 15:58
Sir i am converting  perfectly working code using opencv into javacv it doesnt freeze my laptop . but i dont want to waste extra time on learning Javacv wrapper methods , types. 
so i tried to convert opencv Mat to javacv so i can easily access grabbedframed into opencv Mat ..
But when i do that it freezes my laptop ..
This is my exact code .using opencv
```
    public static void main(String[] args) throws InterruptedException {
        System.loadLibrary(Core.NATIVE_LIBRARY_NAME);
        initGUI();
        VideoCapture capVideo = new VideoCapture("/home/mnh/Desktop/cars.mp4");
        Image tempImage;
        Mat imgFrame1 = new Mat();
        Mat imgFrame2 = new Mat();
         ArrayList<MatOfPoint> hullContours=new ArrayList<MatOfPoint>();
        ArrayList<Blob> blobs = new ArrayList<>();
        Point[] crossingLine = new Point[2];
        crossingLine[0] = new Point();
        crossingLine[1] = new Point();
        int carCount = 0;
        if (!capVideo.isOpened()) {
            System.out.println("Error Reading File");
        }
        if (capVideo.get(Videoio.CAP_PROP_FRAME_COUNT) < 2) {
            System.out.println("Error video must have at least two frames");
        }

        capVideo.read(imgFrame1);
        capVideo.read(imgFrame2);

        
        //For Creating Vertical Line
        
        int intHorizontalLinePosition = (int) Math.round((double) imgFrame1.cols() * 0.5);
        crossingLine[0].x = intHorizontalLinePosition;
        crossingLine[0].y = 0;

        crossingLine[1].x = intHorizontalLinePosition;
        crossingLine[1].y = imgFrame1.rows() - 1;


//        int intHorizontalLinePosition = (int) Math.round((double) imgFrame1.rows() * 0.5);
//        crossingLine[0].x = 0;
//        crossingLine[0].y = intHorizontalLinePosition;
//
//        crossingLine[1].x = imgFrame1.cols() - 1;
//        crossingLine[1].y = intHorizontalLinePosition;

        char chCheckForEscKey = 0;

        boolean blnFirstFrame = true;

        int frameCount = 2;


        while (capVideo.isOpened() ) {
           // Thread.sleep(100);
          //capVideo.read(imgFrame1);
          //capVideo.read(imgFrame2);
            ArrayList<Blob> currentFrameBlobs = new ArrayList<>();
            Mat imgFrame1Copy = imgFrame1.clone();
            Mat imgFrame2Copy = imgFrame2.clone();
            Mat imgDifference = new Mat();
            Mat imgThresh = new Mat();

            Imgproc.cvtColor(imgFrame1Copy, imgFrame1Copy, Imgproc.COLOR_BGR2GRAY, 0);
            Imgproc.cvtColor(imgFrame2Copy, imgFrame2Copy, Imgproc.COLOR_BGR2GRAY, 0);

            Imgproc.GaussianBlur(imgFrame1Copy, imgFrame1Copy, new Size(5, 5), 0);
            Imgproc.GaussianBlur(imgFrame2Copy, imgFrame2Copy, new Size(5, 5), 0);
            Core.absdiff(imgFrame1Copy, imgFrame2Copy, imgDifference);

            Imgproc.threshold(imgDifference, imgThresh, 30, 255, Imgproc.THRESH_BINARY);
                        ImageViewer iv=new ImageViewer();
           // iv.show(imgThresh);
            Mat structuringElement3x3 = getStructuringElement(Imgproc.MORPH_RECT, new Size(3, 3));
            Mat structuringElement5x5 = getStructuringElement(Imgproc.MORPH_RECT, new Size(5, 5));
            Mat structuringElement7x7 = getStructuringElement(Imgproc.MORPH_RECT, new Size(7, 7));
            Mat structuringElement15x15 = getStructuringElement(Imgproc.MORPH_RECT, new Size(15, 15));

            for (int i = 0; i < 2; i++) {
                Imgproc.dilate(imgThresh, imgThresh, structuringElement7x7);
                Imgproc.dilate(imgThresh, imgThresh, structuringElement7x7);
                Imgproc.erode(imgThresh, imgThresh, structuringElement5x5);
            }

            Mat imgThreshCopy = imgThresh.clone();
            ArrayList<MatOfPoint> contours = new ArrayList<>();
            Imgproc.findContours(imgThreshCopy, contours, new Mat(), Imgproc.RETR_EXTERNAL, Imgproc.CHAIN_APPROX_SIMPLE);

           Mat imgContours=  drawAndShowContours(imgThresh.size(), contours, "imgContours");
           Mat imgConvexHulls=new Mat();

           
            for (int i = 0; i < contours.size(); i++) {
              //  System.out.println("Printing Convexs");
              hullContours.add(getConvexHull(contours.get(i),contours));
            }
            
            imgConvexHulls=  drawAndShowContours(imgThresh.size(), hullContours, "imgConvexHulls");

            
            for (MatOfPoint hullContour : hullContours) {
            //    System.out.println("Here iam "+contours.size());
                Blob possibleBlob = new Blob(hullContour);

                if (possibleBlob.currentBoundingRect.area() > 400
                        && possibleBlob.dblCurrentAspectRatio > 0.2
                        && possibleBlob.dblCurrentAspectRatio < 4.0
                        && possibleBlob.currentBoundingRect.width > 30
                        && possibleBlob.currentBoundingRect.height > 30
                        && possibleBlob.dblCurrentDiagonalSize > 60.0
                        && (Imgproc.contourArea(possibleBlob.currentContour) / (double) possibleBlob.currentBoundingRect.area()) > 0.50) {
                    currentFrameBlobs.add(possibleBlob);
                }
            }
            hullContours.clear();
           imgConvexHulls=  drawAndShowContour(imgThresh.size(), currentFrameBlobs, "imgCurrentFrameBlobs");
            
            if (blnFirstFrame == true) {
                for (Blob currentFrameBlob : currentFrameBlobs) {
                    blobs.add(currentFrameBlob);
                }
            } else {
              blobs=  matchCurrentFrameBlobsToExistingBlobs(blobs, currentFrameBlobs);
            }

             drawAndShowContour(imgThresh.size(), blobs, "imgBlobs");

            imgFrame2Copy = imgFrame2.clone();          // get another copy of frame 2 since we changed the previous frame 2 copy in the processing above

            drawBlobInfoOnImage(blobs, imgFrame2Copy);

            ArrayList<Object> checking=  checkIfBlobsCrossedTheLine(blobs, intHorizontalLinePosition, carCount);
            boolean blnAtLeastOneBlobCrossedTheLine = (boolean) checking.get(0);
            blobs=(ArrayList<Blob>) checking.get(1);
            carCount=(int) checking.get(2);
            if (blnAtLeastOneBlobCrossedTheLine == true) {
                Imgproc.line(imgFrame2Copy, crossingLine[0], crossingLine[1], new Scalar(0, 200, 0), 2);
            } else {
                Imgproc.line(imgFrame2Copy, crossingLine[0], crossingLine[1], new Scalar(0, 0, 255), 2);
            }

          drawCarCountOnImage(carCount, imgFrame2Copy);
      
          int count=0;
          for(int i=0;i<blobs.size();i++)
          {
              if(blobs.get(i).blnStillBeingTracked==true)
              {
                  count++;
              }
          }
          int congestionThreshold=7;
          if(count >congestionThreshold)
          {
              System.out.println("There is much Traffic");
          }
          
          currentFrameBlobs.clear();

            imgFrame1 = imgFrame2.clone();           // move frame 1 up to where frame 2 is

            
             if ((capVideo.get(Videoio.CAP_PROP_POS_FRAMES) + 1) < capVideo.get(Videoio.CAP_PROP_FRAME_COUNT)) {
            capVideo.read(imgFrame2);
        }
        else {
            System.out.print("end of video");
            break;
        }
            
            
            blnFirstFrame = false;
            frameCount++;
         //   System.out.println(carCount);
            tempImage = toBufferedImage(imgFrame2Copy);
            ImageIcon imageIcon = new ImageIcon(tempImage, "Captured video");

            imageLabel.setIcon(imageIcon);
            frame.pack(); //this will resize the window to fit the image

        }

    }

```

**Comment by mnh-aj123** [comment] 2017-05-04 20:15
@saudet  any solution ?

**Comment by mnh-aj123** [comment] 2017-05-05 13:30
@saudet  any response i m in immediate need . Kindly respond

**Comment by saudet** [comment] 2017-05-05 13:43
This is only going to work if you use the same version of OpenCV for both Java wrappers. What version of OpenCV and JavaCV are you trying to use together?

**Comment by mnh-aj123** [comment] 2017-05-05 13:51
opencv 3.2.0 and javacv 1.2 @saudet

**Comment by mnh-aj123** [comment] 2017-05-05 13:53
and i also used opencv 3.1.0 with javacv 1.2

**Comment by saudet** [comment] 2017-05-05 14:08
So try again with JavaCV 1.3.2

**Comment by mnh-aj123** [comment] 2017-05-05 15:18
@saudet  i used javaCV but new error arises .
   A fatal error has been detected by the Java Runtime Environment:

  SIGSEGV (0xb) at pc=0x00007f6cd05f1496, pid=3642, tid=0x00007f6ccc1f0700

 JRE version: Java(TM) SE Runtime Environment (8.0_131-b11) (build 1.8.0_131-b11)
 Java VM: Java HotSpot(TM) 64-Bit Server VM (25.131-b11 mixed mode linux-amd64 compressed oops)
 Problematic frame:
 V  [libjvm.so+0x985496]  PSParallelCompact::IsAliveClosure::do_object_b(oopDesc*)+0x36

 Core dump written. Default location: /home/mnh/NetBeansProjects/JavaCvApplications/core or core.3642

 If you would like to submit a bug report, please visit:
   http://bugreport.java.com/bugreport/crash.jsp

Stack: [0x00007f6ccc0f0000,0x00007f6ccc1f1000],  sp=0x00007f6ccc1ef300,  free space=1020k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
V  [libjvm.so+0x985496]  PSParallelCompact::IsAliveClosure::do_object_b(oopDesc*)+0x36
V  [libjvm.so+0x46b000]  ClassLoaderDataGraph::do_unloading(BoolObjectClosure*, bool)+0x70
V  [libjvm.so+0xa3665c]  SystemDictionary::do_unloading(BoolObjectClosure*, bool)+0x1c
V  [libjvm.so+0x987271]  PSParallelCompact::marking_phase(ParCompactionManager*, bool, ParallelOldTracer*)+0x4c1
V  [libjvm.so+0x98c42e]  PSParallelCompact::invoke_no_policy(bool)+0x40e
V  [libjvm.so+0x98cca3]  PSParallelCompact::invoke(bool)+0x63
V  [libjvm.so+0xac9dc8]  VM_ParallelGCSystemGC::doit()+0xa8
V  [libjvm.so+0xad1765]  VM_Operation::evaluate()+0x55
V  [libjvm.so+0xacfb3a]  VMThread::evaluate_operation(VM_Operation*)+0xba
V  [libjvm.so+0xacfebe]  VMThread::loop()+0x1ce
V  [libjvm.so+0xad0330]  VMThread::run()+0x70
V  [libjvm.so+0x927568]  java_start(Thread*)+0x108

VM_Operation (0x00007f6cd184af30): ParallelGCSystemGC, mode: safepoint, requested by thread 0x00007f6cc800c000

**Comment by mnh-aj123** [comment] 2017-05-05 18:53
@saudet  kindly make this question open so other user's may also give some input ?

**Comment by saudet** [comment] 2017-05-06 01:08
As we can see from https://github.com/bytedeco/javacpp/issues/38
it works fine for everyone else!

So please provide a smaller sample to reproduce your issue and we'll see
what we can do. No one is going to do all the work for you for free,
especially when the issue is probably with your application and not with
JavaCV.
