### ISSUE TITLE
Open CV 4.8.0 integration

### ISSUE THREAD

**Issue by aino-gautam** [bytedeco/javacpp#713] opened 2023-09-30 05:26 UTC
Is there implementation / support for OpenCV 4.8 with JavaCPP ? Can you please point me to the repo site ?

**Comment by saudet** [comment] 2023-09-30 06:36
Please try again with the snapshots: http://bytedeco.org/builds/

**Comment by saudet** [comment] 2023-10-04 23:14
Duplicate of https://github.com/bytedeco/javacv/issues/2087

**Closed by saudet** 2023-10-04 23:14 UTC
Labels: duplicate, enhancement
