### ISSUE TITLE
Android studio runtime error

### ISSUE THREAD

**Issue by zkrige** [bytedeco/javacpp#257] opened 2018-09-07 06:19 UTC
I'm trying to use javacpp inside Android Studio. My app seems to compile fine, but when at runtime I get the following error

`java.lang.UnsatisfiedLinkError: No implementation found for void com.apextechnology.swid.WrapperLoader.allocate(java.lang.String)`

In WrapperLoader.java I have the following

```
package com.apextechnology.swid;

import org.bytedeco.javacpp.BytePointer;
import org.bytedeco.javacpp.Pointer;
import org.bytedeco.javacpp.annotation.*;
@Platform(include = "sdkinclude.h", library = "sdkwrap")
public class WrapperLoader extends Pointer
{
     public WrapperLoader(String appDomain)
    {
        allocate(appDomain);
    }

  @Allocator
    private native void allocate(@StdString String pckg);

    static
    {
        System.loadLibrary("sdkwrap");
    }
}
```

in Android.mk I have

```
LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)
LOCAL_MODULE    := sdkwrap
LOCAL_SRC_FILES :=  /* cpp files listed here */
include $(BUILD_SHARED_LIBRARY)
```

Clearly I'm missing something

Can you advise on how to properly configure Android Studio so that the entire build process is automatic?

**Comment by saudet** [comment] 2018-09-07 06:29
Marking this as duplicate of issues #52 and #69. We have to call JavaCPP as part of the build.
Thanks to @leaf918 there is a sample project for that here:
https://github.com/bytedeco/sample-projects/tree/master/javacpp-android-gradle
But to make this nice, we'd need a plugin for Gradle...

**Closed by saudet** 2018-09-07 06:29 UTC
Labels: duplicate, question

**Comment by zkrige** [comment] 2018-09-07 09:42
Perhaps this should be added to wiki

**Comment by saudet** [comment] 2018-09-07 09:48
Yeah, this could be updated:
https://github.com/bytedeco/javacpp/wiki/Using-Android-NDK
Feel free to modify that or create a new page!

**Comment by zkrige** [comment] 2018-09-07 10:52
Still no luck. It appears the compile is happy, but my app is not finding what it needs

```
android.libraryVariants.all{ variant ->
    variant.outputs.all {output ->
        def projectDir = project.projectDir.absolutePath
        def classesDir = variant.javaCompile.destinationDir
        def jniDir = file("$projectDir/src/main/cpp/").absolutePath
        def stdioPath = "$ndkPath/sources/android/support/include/"
        def platformIncl = "$ndkPath/sources/cxx-stl/gnu-libstdc++/4.9/include/"
        def jniIncl = "$ndkPath/sysroot/usr/include/"
        variant.javaCompile.doLast {
            println '===javacpp start==='

            println '32bit compile'
            //build 32bit so
            def arch = "armeabi-v7a"
            def compilePath = "$ndkPath/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/bin/arm-linux-androideabi-gcc"
            def sysRoot = "$ndkPath/platforms/android-28/arch-arm"
            def stlIncl = "$ndkPath/sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi-v7a"
            def archIncl = "$ndkPath/sysroot/usr/include/arm-linux-androideabi/"
            def bitsPath = "$stlIncl/include"
            def includePath = "$platformIncl:$stlIncl:$stdioPath:$platformIncl:$jniIncl:$archIncl:$bitsPath:$jniDir"
            android.defaultConfig.externalNativeBuild.cmake.setCppFlags(["-std=c++11", "-frtti", "-fexceptions"])
            javaexec {
                main = 'org.bytedeco.javacpp.tools.Builder'
                classpath = files(configurations.javacpp.asPath)
                args = [
                        '-cp', "$classesDir",
                        '-properties', "$arch",
                        "-Dplatform.root=$ndkPath",
                        "-Dplatform.compiler=$compilePath",
                        "-Dplatform.includepath=$includePath",
                        "-d", "$jniDir/$arch/",
                        "-Xcompiler", "--sysroot=$sysRoot",
                        "-Xcompiler", "-std=gnu++11",
                        "-Xcompiler", "-fpermissive"
                ]
            }
        }
        println '===javacpp done==='
    }
}
```

the lib.so files are created in the expected folder, but at runtime I still get `no implementation found error`

**Comment by saudet** [comment] 2018-09-07 12:50
If you set the "org.bytedeco.javacpp.logger.debug" system property to
"true", what do you get in the log?

**Comment by zkrige** [comment] 2018-09-07 14:09
```
android.libraryVariants.all{ variant ->
    System.setProperty("org.bytedeco.javacpp.logger.debug","true")
    variant.outputs.all {output ->
        def projectDir = project.projectDir.absolutePath
        def classesDir = variant.javaCompile.destinationDir
        def jniDir = file("$projectDir/src/main/cpp/").absolutePath
        def stdioPath = "$ndkPath/sources/android/support/include/"
        def platformIncl = "$ndkPath/sources/cxx-stl/gnu-libstdc++/4.9/include/"
        def jniIncl = "$ndkPath/sysroot/usr/include/"
        variant.javaCompile.doLast {
            println '===javacpp start==='

            println '32bit compile'
            //build 32bit so
            def arch = "armeabi-v7a"
            def compilePath = "$ndkPath/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/bin/arm-linux-androideabi-gcc"
            def sysRoot = "$ndkPath/platforms/android-28/arch-arm"
            def stlIncl = "$ndkPath/sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi-v7a"
            def archIncl = "$ndkPath/sysroot/usr/include/arm-linux-androideabi/"
            def bitsPath = "$stlIncl/include"
            def includePath = "$platformIncl:$stlIncl:$stdioPath:$platformIncl:$jniIncl:$archIncl:$bitsPath:$jniDir"
            javaexec {
                main = 'org.bytedeco.javacpp.tools.Builder'
                classpath = files(configurations.javacpp.asPath)
                args = [
                        '-cp', "$classesDir",
                        '-properties', "$arch",
                        "-Dplatform.root=$ndkPath",
                        "-Dplatform.compiler=$compilePath",
                        "-Dplatform.includepath=$includePath",
                        //"-d", "$jniDir/$arch/",
                        "-d", "src/main/jniLibs/$arch/",
                        "-Xcompiler", "--sysroot=$sysRoot",
                        "-Xcompiler", "-std=gnu++11",
                        "-Xcompiler", "-fpermissive",
                        "-Xcompiler", "-frtti",
                        "-Xcompiler", "-fexceptions",
                        "-Xcompiler", "-Wno-attributes",
                        "-Xcompiler", "-Wno-unused-variable",
                        "-Xcompiler", "-Wno-sign-compare",
                ]
            }
            println '===javacpp done==='
        }
    }
}
```

yields

```
===javacpp start===
32bit compile
Warning: Could not load platform properties for class android.arch.core.R
Warning: Could not load platform properties for class android.arch.lifecycle.R
Warning: Could not load platform properties for class android.arch.lifecycle.livedata.core.R
Warning: Could not load platform properties for class android.arch.lifecycle.viewmodel.R
Warning: Could not load platform properties for class android.support.compat.R
Warning: Could not load platform properties for class android.support.coreui.R
Warning: Could not load platform properties for class android.support.coreutils.R
Warning: Could not load platform properties for class android.support.fragment.R
Warning: Could not load platform properties for class android.support.graphics.drawable.R
Warning: Could not load platform properties for class android.support.graphics.drawable.animated.R
Warning: Could not load platform properties for class android.support.mediacompat.R
Warning: Could not load platform properties for class android.support.v4.R
Warning: Could not load platform properties for class android.support.v7.appcompat.R
Warning: Could not load platform properties for class com.apextechnology.driverscan.BuildConfig
Warning: Could not load platform properties for class com.apextechnology.driverscan.R
Warning: Could not load platform properties for class com.apextechnology.driverscan.activation.AbstractEncryptor
Warning: Could not load platform properties for class com.apextechnology.driverscan.activation.CryptoException
Warning: Could not load platform properties for class com.apextechnology.driverscan.activation.DriversScanner
Warning: Could not load platform properties for class com.apextechnology.driverscan.activation.EncryptorImplAES
Warning: Could not load platform properties for class com.apextechnology.driverscan.activation.Loader
Warning: Could not load platform properties for class com.apextechnology.driverscan.activation.Shared
Warning: Could not load platform properties for class com.apextechnology.driverscan.activation.TextUtil
Warning: Could not load platform properties for class com.apextechnology.driverscan.activation.client.ErrorMessages
Warning: Could not load platform properties for class com.apextechnology.driverscan.activation.client.LicenseValidator
Warning: Could not load platform properties for interface com.apextechnology.driverscan.activation.client.OnlineLicenseCallback
Warning: Could not load platform properties for class com.apextechnology.driverscan.activation.client.OnlineLicenseValidator
Warning: Could not load platform properties for class com.apextechnology.driverscan.dto.Card
Warning: Could not load platform properties for class com.apextechnology.driverscan.dto.CompressedImage
Warning: Could not load platform properties for class com.apextechnology.driverscan.dto.DateFormatter
Warning: Could not load platform properties for class com.apextechnology.driverscan.dto.DrivingLicense
Warning: Could not load platform properties for class com.apextechnology.driverscan.dto.DrivingLicenseCard
Warning: Could not load platform properties for class com.apextechnology.driverscan.dto.GlobalBarcodeLicenseDto
Warning: Could not load platform properties for class com.apextechnology.driverscan.dto.IdentityDocument
Warning: Could not load platform properties for class com.apextechnology.driverscan.dto.Person
Warning: Could not load platform properties for class com.apextechnology.driverscan.dto.ProfessionalDrivingPermit
Warning: Could not load platform properties for class com.apextechnology.driverscan.dto.VehicleClass
Warning: Could not load platform properties for class com.apextechnology.driverscan.helper.RawBitmap
Warning: Could not load platform properties for class com.apextechnology.driverscan.pvt.BarCodeLicenseDecipher
Warning: Could not load platform properties for class com.apextechnology.driverscan.pvt.BarCodeLicenseDecipherHelper
Warning: Could not load platform properties for class com.apextechnology.driverscan.pvt.Keys
Warning: Could not load platform properties for class com.apextechnology.driverscan.pvt.PhotoDataHelper
Warning: Could not load platform properties for class com.apextechnology.driverscan.pvt.ValidatorDependencies
Warning: Could not load platform properties for class com.apextechnology.driverscan.pvt.helper.CertificateHelper
Warning: Could not load platform properties for class com.apextechnology.driverscan.pvt.helper.Decipher
Warning: Could not load platform properties for class com.apextechnology.driverscan.pvt.helper.RawImage
Warning: Could not load platform properties for class com.apextechnology.driverscan.pvt.helper.ValidatorHelper
Warning: Could not load platform properties for class com.apextechnology.driverscan.pvt.parser.BarcodeLicenseConstants
Warning: Could not load platform properties for class com.apextechnology.driverscan.pvt.parser.BarcodeLicenseParser
Warning: Could not load platform properties for class com.apextechnology.driverscan.pvt.parser.BinaryDataSectionParser
Warning: Could not load platform properties for class com.apextechnology.driverscan.pvt.parser.HeadersSectionParser
Warning: Could not load platform properties for interface com.apextechnology.driverscan.pvt.parser.SectionParser
Warning: Could not load platform properties for class com.apextechnology.driverscan.pvt.parser.StringsSectionParser
Warning: Could not load platform properties for class com.google.android.gms.base.R
Warning: Could not load platform properties for class com.google.android.gms.common.R
Warning: Could not load platform properties for class com.google.android.gms.safetynet.R
Warning: Could not load platform properties for class com.google.android.gms.tasks.R
Generating /Users/zayinkrige/Dropbox/Business/DriverScan/Android/Library/Driverscan/src/main/jniLibs/armeabi-v7a/jnijavacpp.cpp
Generating /Users/zayinkrige/Dropbox/Business/DriverScan/Android/Library/Driverscan/src/main/jniLibs/armeabi-v7a/sdkwrap.cpp
Compiling /Users/zayinkrige/Dropbox/Business/DriverScan/Android/Library/Driverscan/src/main/jniLibs/armeabi-v7a/libsdkwrap.so
/Users/zayinkrige/android-sdks/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/bin/arm-linux-androideabi-gcc -I/Users/zayinkrige/android-sdks/ndk-bundle/sources/cxx-stl/gnu-libstdc++/4.9/include/ -I/Users/zayinkrige/android-sdks/ndk-bundle/sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi-v7a -I/Users/zayinkrige/android-sdks/ndk-bundle/sources/android/support/include/ -I/Users/zayinkrige/android-sdks/ndk-bundle/sysroot/usr/include/ -I/Users/zayinkrige/android-sdks/ndk-bundle/sysroot/usr/include/arm-linux-androideabi/ -I/Users/zayinkrige/android-sdks/ndk-bundle/sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi-v7a/include -I/Users/zayinkrige/Dropbox/Business/DriverScan/Android/Library/Driverscan/src/main/cpp '-I/Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/include' '-I/Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/include/darwin' /Users/zayinkrige/Dropbox/Business/DriverScan/Android/Library/Driverscan/src/main/jniLibs/armeabi-v7a/sdkwrap.cpp /Users/zayinkrige/Dropbox/Business/DriverScan/Android/Library/Driverscan/src/main/jniLibs/armeabi-v7a/jnijavacpp.cpp -O3 --sysroot=/Users/zayinkrige/android-sdks/ndk-bundle/platforms/android-28/arch-arm -std=gnu++11 -fpermissive -frtti -fexceptions -Wno-attributes -Wno-unused-variable -Wno-sign-compare -Wall -fPIC -shared -o libsdkwrap.so 
Deleting /Users/zayinkrige/Dropbox/Business/DriverScan/Android/Library/Driverscan/src/main/jniLibs/armeabi-v7a/sdkwrap.cpp
Deleting /Users/zayinkrige/Dropbox/Business/DriverScan/Android/Library/Driverscan/src/main/jniLibs/armeabi-v7a/jnijavacpp.cpp
===javacpp done===
```

@saudet I have dropped you mail on contact @ bytedeco dot org regarding commercial support

**Comment by zkrige** [comment] 2018-09-07 14:16
ergh. android. ¯\\_(ツ)_/¯ 

so now with no changes, its giving me this error

```
java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "_ZNSs4_Rep20_S_empty_rep_storageE" referenced by "libsdkwrap.so"...
        at java.lang.Runtime.loadLibrary(Runtime.java:372)
        at java.lang.System.loadLibrary(System.java:988)
        at com.apextechnology.swid.WrapperLoader.<clinit>(WrapperLoader.java:42)
```

```
@Platform(include = "sdkinclude.h", library = "sdkwrap")
public class WrapperLoader extends Pointer
{
    /**
    * appDomain - must be application's package as in manifest, used to find DLL library in cache by C++ code
     */
    public WrapperLoader(String appDomain)
    {
        allocate(appDomain);
    }

/** removed sensitive code */

    @Allocator
    private native void allocate(@StdString String pckg);

    static
    {
        System.loadLibrary("sdkwrap");
    }
}
```

**Comment by saudet** [comment] 2018-09-10 09:53
It's not loading the properties and thus not linking with the C++ library, that's what's wrong. Replace `'-properties', "$arch",` with `'-properties', 'android-arm'` as shown in the sample project here:
https://github.com/bytedeco/sample-projects/blob/master/javacpp-android-gradle/app/build.gradle#L72
And similarly for other architectures:
https://github.com/bytedeco/javacpp/tree/master/src/main/resources/org/bytedeco/javacpp/properties

**Comment by zkrige** [comment] 2018-09-10 10:10
ah good catch!

however, i'm now getting this linking error
`/Users/zayinkrige/android-sdks/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: cannot find -lgnustl_static`

mdfind returns me this

``` mdfind libgnustl_static
/Users/zayinkrige/android-sdks/ndk-bundle/sources/cxx-stl/gnu-libstdc++/4.9/libs/mips/libgnustl_static.a
/Users/zayinkrige/android-sdks/ndk-bundle/sources/cxx-stl/gnu-libstdc++/4.9/libs/mips64/libgnustl_static.a
/Users/zayinkrige/android-sdks/ndk-bundle/sources/cxx-stl/gnu-libstdc++/4.9/libs/arm64-v8a/libgnustl_static.a
/Users/zayinkrige/android-sdks/ndk-bundle/sources/cxx-stl/gnu-libstdc++/4.9/libs/x86/libgnustl_static.a
/Users/zayinkrige/android-sdks/ndk-bundle/sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi-v7a/libgnustl_static.a
/Users/zayinkrige/android-sdks/ndk-bundle/sources/cxx-stl/gnu-libstdc++/4.9/libs/x86_64/libgnustl_static.a
```

so the include path SEEMS to be correct

```
android.libraryVariants.all{ variant ->
    System.setProperty("org.bytedeco.javacpp.logger.debug","true")
    variant.outputs.all {output ->
        def projectDir = project.projectDir.absolutePath
        def classesDir = variant.javaCompile.destinationDir
        def jniDir = file("$projectDir/src/main/cpp/").absolutePath
        def stdioPath = "$ndkPath/sources/android/support/include/"
        def platformIncl = "$ndkPath/sources/cxx-stl/gnu-libstdc++/4.9/include/"
        def jniIncl = "$ndkPath/sysroot/usr/include/"
        variant.javaCompile.doLast {
            println '===javacpp start==='

            println '32bit compile'
            //build 32bit so
            def compilePath = "$ndkPath/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/bin/arm-linux-androideabi-gcc"
            def sysRoot = "$ndkPath/platforms/android-28/arch-arm/"
            def stlIncl = "$ndkPath/sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi-v7a/"
            def archIncl = "$ndkPath/sysroot/usr/include/arm-linux-androideabi/"
            def bitsPath = "$stlIncl/include/"
            def includePath = "$platformIncl:$stlIncl:$stdioPath:$platformIncl:$jniIncl:$archIncl:$bitsPath:$jniDir"
            javaexec {
                main = 'org.bytedeco.javacpp.tools.Builder'
                classpath = files(configurations.javacpp.asPath)
                args = [
                        '-cp', "$classesDir",
                        '-properties', "android-arm",
                        "-Dplatform.root=$ndkPath",
                        "-Dplatform.compiler=$compilePath",
                        "-Dplatform.includepath=$includePath",
                        "-d", "src/main/jniLibs/armeabi-v7a/",
                        "-Xcompiler", "--sysroot=$sysRoot",
                        "-Xcompiler", "-std=gnu++11",
                        "-Xcompiler", "-fpermissive",
                        "-Xcompiler", "-frtti",
                        "-Xcompiler", "-fexceptions",
                        "-Xcompiler", "-Wno-attributes",
                        "-Xcompiler", "-Wno-unused-variable",
                        "-Xcompiler", "-Wno-sign-compare",
                ]
            }
```

**Comment by zkrige** [comment] 2018-09-10 10:12
aha

i needed to add `"-Dplatform.linkpath=$stlIncl",` and now it seems to find the library

**Comment by saudet** [comment] 2020-05-21 00:42
BTW, a build plugin for Gradle is now available here:
https://github.com/bytedeco/gradle-javacpp
If you try it out and find anything missing, please let me know!

**Comment by zkrige** [comment] 2020-05-21 06:08
this is excellent - thank you so much
