### ISSUE TITLE
Create Preset

### ISSUE THREAD

**Issue by smily75** [bytedeco/javacpp#316] opened 2019-07-03 21:27 UTC
Hi, 
I'm looking at JavaCPP right now and unfortunately I can't get any further. Actually, we thought that using JavaCpp would save us a lot of time. Unfortunately I don't get an example from you to run. I have now tried step by step according to the instructions on the page Create New Presets to get the example to run, but if I do it exactly according to the instructions I get the last step: 
` mvn clean install --projects .,zlib` 

The following error message: 

 [INFO] Scanning for projects...

[ERROR] [ERROR] Could not find the selected project in the reactor: . @

[ERROR] Could not find the selected project in the reactor: . -> [Help 1]

[ERROR]

[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.

[ERROR] Re-run Maven using the -X switch to enable full debug logging.

[ERROR]

[ERROR] For more information about the errors and possible solutions, please read the following articles:

[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MavenExecutionException

I've been trying your framework for 3 days now and slowly I think it might be easier to try JNI. 

Where can I find a detailed manual what I can do in the Mapping Config Java files? The parser does something wrong with `std::map<std::string,tState>& state_map`  and the generated Java class cannot be compiled. 

Sorry, but I am a bit frustrated. 

Best regards 
Sandra

**Comment by saudet** [comment] 2019-07-03 23:18
If you're just looking for something to map a couple of functions quickly, it's better to not try to parse header files, and write the Java interface classes manually. This is a good example we can start from for that use case:
https://github.com/bytedeco/javacpp/wiki/Interface-Thrust-and-CUDA
`std::map<std::string,tState>` is a C++ class just like any other C++ class, but its name contains characters that are not valid for a Java class, so we need to give it a valid name with the `@Name` annotation, but that's about it.

**Comment by smily75** [comment] 2019-07-04 12:22
Hi, thank you.
Sorry for this frustrated request. We got C++ header files as interface (many files) and I can't write C++, so I would like to try parsing. I'm now ready to get some of my header files parsed. But I keep coming into contact with code that can't be parsed correctly. Some adjustments to the InfoMap can be done from the presets, which is very tedious. 
For example, I have a line that I don't understand, maybe you can help me: 

header file:
template <>
bool isOk<Result>(const Result& result);

java file:
@Namespace("a_util::result") public static native @Cast("bool") @Name("isOk<Result>") boolean isOk<Result>(@Const @ByRef Result result);

How can I customize the InfoMap to parse it correctly? 

Thank you

**Comment by saudet** [comment] 2019-07-04 13:10
The parser isn't able to deal with that without help, but there are
"recipes" for common situations here:
https://github.com/bytedeco/javacpp/wiki/Mapping-Recipes#mapping-macros-to-fields-or-methods

**Comment by saudet** [comment] 2019-07-06 00:24
Duplicate of #51 

Once we have better parser support, that will be all automated.

**Closed by saudet** 2019-07-06 00:24 UTC
Labels: duplicate, enhancement

**Comment by saudet** [comment] 2019-07-06 00:28
BTW, there's also a "helloworld" project example these days thanks to @matteodg:
https://github.com/bytedeco/helloworld
