### ISSUE TITLE
After the virtual function in the abstract class is modified by const, how does javacpp map?

### ISSUE THREAD

**Issue by ACCia** [bytedeco/javacpp#333] opened 2019-08-20 08:10 UTC
How can I configure javacpp to map it?

```
class IWinToastHandler
{
	public:
		
		virtual ~IWinToastHandler() = default;
		virtual void toastActivated() const = 0;
		virtual void toastActivated(int actionIndex) const = 0;
		virtual void toastDismissed() const = 0;
		virtual void toastFailed() const = 0;
};
```

**Comment by saudet** [comment] 2019-08-20 10:54
Use the third value of the `@Const` annotation, see: https://github.com/bytedeco/javacpp/pull/224#issuecomment-359774350

**Comment by saudet** [comment] 2019-08-20 10:55
Duplicate of #224

**Closed by saudet** 2019-08-20 10:55 UTC
Labels: duplicate, question
