### ISSUE TITLE
Again `long` type problem

### ISSUE THREAD

**Issue by unit-a-user** [bytedeco/javacpp#578] opened 2022-06-05 18:21 UTC
I expected line such as `(uintptr_t)&ptr->extent;`

```java
        @Name("extent")
        @MemberGetter @Cast("uintptr_t") @ByRef public native long getExtent();
```

But getting wrong code:
```cpp
JNIEXPORT jlong JNICALL Java_org_helixd2s_yavulkanmod_alter_header_CreateInfo_00024ImageCreateInfo_getExtent(JNIEnv* env, jobject obj) {
    ::alter::ImageCreateInfo* ptr = (::alter::ImageCreateInfo*)jlong_to_ptr(env->GetLongField(obj, JavaCPP_addressFID));
    if (ptr == NULL) {
        env->ThrowNew(JavaCPP_getClass(env, 7), "This pointer address is NULL.");
        return 0;
    }
    jlong position = env->GetLongField(obj, JavaCPP_positionFID);
    ptr += position;
    jlong rarg = 0;
    jthrowable exc = NULL;
    try {
        uintptr_t rval = (uintptr_t)ptr->extent;
        rarg = (jlong)rval;
    } catch (...) {
        exc = JavaCPP_handleException(env, 9);
    }

    if (exc != NULL) {
        env->Throw(exc);
    }
    return rarg;
}
```

**Comment by saudet** [comment] 2022-06-06 00:29
Duplicate of #576

**Closed by saudet** 2022-06-06 00:29 UTC
Labels: bug, duplicate

**Comment by Zack-asdf776** [comment] 2026-07-10 02:24
hi, my `@Cast("uintptr_t") @ByRef` getter returns the wrong number — looks like the value instead of the address:
 
```java
@Name("extent")
@MemberGetter @Cast("uintptr_t") @ByRef
public native long ...;
```
 
generated:
 
```cpp
uintptr_t rval = (uintptr_t)ptr->extent;   // expected &(ptr->extent)
```
 
 so I end up using it as a bad pointer. Is `@ByRef` supposed to still take the address for a non-pointer cast? (latest snapshot)

**Comment by saudet** [comment] 2026-07-10 03:01
Sounds like what you're looking for is `p.address() + p.offsetof("extent")`
