### ISSUE TITLE
CLI regression introduced in 1.5.1

### ISSUE THREAD

**Issue by rafeememon** [bytedeco/javacpp#596] opened 2022-07-30 20:52 UTC
I'm encountering an issue running the builder from the command line when upgrading from version 1.4.4 to 1.5.7 - I'm very behind 😊.  It appears that https://github.com/bytedeco/javacpp/commit/7a9ac9cfb647e9850a1bcd2aec829751704a7457 introduced in 1.5.1 removed (unintentionally, based on the commit message?) the ability to omit the class/package paths when running the builder CLI.  My setup omits the package to automatically find the Java sources needing native code, but strangely, it isn't able to find the sources when I add a package wildcard (probably just needs more digging in my project).  I'm happy to submit a patch if this is indeed an unintended regression.

Problematic diff here: https://github.com/bytedeco/javacpp/commit/7a9ac9cfb647e9850a1bcd2aec829751704a7457#diff-e9f06b9457428e2edbb75f4abab2cd3870566f2d77c6219ae94bfa1153d37f59R1325

**Comment by rafeememon** [comment] 2022-07-30 23:22
Ah, it seems I missed this issue: https://github.com/bytedeco/javacv/issues/1311 After some fiddling with my setup, I'm now running into some `The process cannot access the file because it is being used by another process` errors, possibly related to https://github.com/bytedeco/javacpp/issues/197, but more likely due to my Gradle task structure.  Will see if I can repro in a smaller example, but the main issue in this ticket is probably a non-issue.

**Comment by saudet** [comment] 2022-08-01 10:43
Duplicate of https://github.com/bytedeco/javacv/issues/1311

**Closed by saudet** 2022-08-01 10:43 UTC
Labels: bug, duplicate
