### ISSUE TITLE
how to call function with reference parameter for return value.

### ISSUE THREAD

**Issue by leechor** [bytedeco/javacpp#467] opened 2021-03-12 11:30 UTC
[public native @Cast("bool") boolean set_config(@Const @ByRef StringStringMap config, @StdString @ByRef BytePointer error);](https://github.com/bytedeco/javacpp-presets/blob/32d981f942d614a38b5f1e9de9121a1ec2548934/ngraph/src/gen/java/org/bytedeco/ngraph/Backend.java#L129)

"@param error An error string describing any error encountered", this parameter is `string &` type in c++,  but how to pass BytePointer when java call this function.

**Comment by supergrecko** [comment] 2021-03-12 11:37
We're using an out parameter here. It expects us to pass a bytepointer and if an error occured it'll change the bytepointer's content.

The following snippet should work

```java
BytePointer err = new BytePointer();
set_config(x, err);
// an error medsage from outparam would be available in the bytepointer.
String s = err.getString();
```

**Comment by leechor** [comment] 2021-03-12 11:47
> We're using an out parameter here. It expects us to pass a bytepointer and if an error occured it'll change the bytepointer's content.
> 
> The following snippet should work
> 
> ```java
> BytePointer err = new BytePointer();
> set_config(x, err);
> // an error medsage from outparam would be available in the bytepointer.
> String s = err.getString();
> ```

I have a private .so , one function just like this, but when I call this function as you does, it not work, 
`Exception in thread "main" java.lang.NullPointerException: Pointer address of argument 8 is NULL.`.

**Comment by supergrecko** [comment] 2021-03-12 12:13
Sorry, I believe the BytePointer should be initialized with a size so it doesn't point to null. Try using something like `new BytePointer(1);`

**Comment by leechor** [comment] 2021-03-12 12:16
> Sorry, I believe the BytePointer should be initialized with a size so it doesn't point to null. Try using something like `new BytePointer(1);`
I had tried, but this error:
` undefined symbol: _ZN14CAntennaModels15CalAntennaModelENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEddddddPdRS5_`

**Comment by supergrecko** [comment] 2021-03-12 12:21
That output is demangled into `CAntennaModels::CalAntennaModel(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, double, double, double, double, double, double, double*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)`, aka `CAntennaModels::CalAntennamodel(std::string, double, double, double, double, double, double, double *, std::string &)`

Is this the signature of your function?

**Comment by leechor** [comment] 2021-03-12 12:24
it is,
`  bool CalAntennaModel(string AntennaModelName, double Phi, double D, double frq, double Eta, double Theta, double GainFloor, double *res, string& errstring);`
the generation is:
`  public native @Cast("bool") boolean CalAntennaModel(@StdString BytePointer AntennaModelName, double Phi, double D, double frq, double Eta, double Theta, double GainFloor, DoublePointer res, @StdString @ByRef BytePointer errstring);
  public native @Cast("bool") boolean CalAntennaModel(@StdString String AntennaModelName, double Phi, double D, double frq, double Eta, double Theta, double GainFloor, DoubleBuffer res, @StdString @ByRef BytePointer errstring);
  public native @Cast("bool") boolean CalAntennaModel(@StdString BytePointer AntennaModelName, double Phi, double D, double frq, double Eta, double Theta, double GainFloor, double[] res, @StdString @ByRef BytePointer errstring);
  public native @Cast("bool") boolean CalAntennaModel(@StdString String AntennaModelName, double Phi, double D, double frq, double Eta, double Theta, double GainFloor, DoublePointer res, @StdString @ByRef BytePointer errstring);
  public native @Cast("bool") boolean CalAntennaModel(@StdString BytePointer AntennaModelName, double Phi, double D, double frq, double Eta, double Theta, double GainFloor, DoubleBuffer res, @StdString @ByRef BytePointer errstring);
  public native @Cast("bool") boolean CalAntennaModel(@StdString String AntennaModelName, double Phi, double D, double frq, double Eta, double Theta, double GainFloor, double[] res, @StdString @ByRef BytePointer errstring);`

**Comment by supergrecko** [comment] 2021-03-12 12:35
That's a linker error. Can you see if the symbol is in the shared library?

```
nm "library.so" | c++filt
```

**Comment by leechor** [comment] 2021-03-12 13:08
other functions in this .so couble be invoke by java.
the nm about this function return is 
`
0000000000009e40 T Java_org_bytedeco_spectrum_CAntennaModels_CalAntennaModel__Ljava_lang_String_2DDDDDDLjava_nio_DoubleBuffer_2Lorg_bytedeco_javacpp_BytePointer_2
000000000000a670 T Java_org_bytedeco_spectrum_CAntennaModels_CalAntennaModel__Ljava_lang_String_2DDDDDDLorg_bytedeco_javacpp_DoublePointer_2Lorg_bytedeco_javacpp_BytePointer_2
000000000000b7d0 T Java_org_bytedeco_spectrum_CAntennaModels_CalAntennaModel__Ljava_lang_String_2DDDDDD_3DLorg_bytedeco_javacpp_BytePointer_2
000000000000adb0 T Java_org_bytedeco_spectrum_CAntennaModels_CalAntennaModel__Lorg_bytedeco_javacpp_BytePointer_2DDDDDDLjava_nio_DoubleBuffer_2Lorg_bytedeco_javacpp_BytePointer_2
0000000000009520 T Java_org_bytedeco_spectrum_CAntennaModels_CalAntennaModel__Lorg_bytedeco_javacpp_BytePointer_2DDDDDDLorg_bytedeco_javacpp_DoublePointer_2Lorg_bytedeco_javacpp_BytePointer_2
000000000000bee0 T Java_org_bytedeco_spectrum_CAntennaModels_CalAntennaModel__Lorg_bytedeco_javacpp_BytePointer_2DDDDDD_3DLorg_bytedeco_javacpp_BytePointer_2
...
000000000000f930 T Java_org_bytedeco_spectrum_global_spectrum_fe
                 w _ITM_deregisterTMCloneTable
                 w _ITM_registerTMCloneTable
                 U _Unwind_Resume
                 U _ZN14CAntennaModels15CalAntennaModelENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEddddddPdRS5_
                 U _ZN14CAntennaModels20GetAntennaModelCountEv
                 U _ZN14CAntennaModels23GetAntennaModelNameListERSt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS6_EE
                 U _ZN14CAntennaModels23GetPeekGainAndBandwidthEdddPdS0_
                 U _ZN14CAntennaModels24GetDiameterAndEfficiencyEdddPdS0_
                 U _ZN14CAntennaModels6DeleteEv
                 U _ZN14CAntennaModels8InstanceEv
                 U _ZN14CAntennaModelsC1Ev
                 U _ZN14CAntennaModelsD1Ev
`

**Comment by supergrecko** [comment] 2021-03-12 14:32
That's the nm output for the libjniX.so library, right? I'm more curious about the nm output for your library. The JavaCPP code generator will declare an undefined (U in nm's output) which will be resolved by the dynamic linker when ran. This is intended behaviour as we're linking multiple shared libraries together at runtime.

The undefined symbol error is reported by the dynamic linker because it failed to resolve where the symbol points to, which means it has no "implementation" to link to. Does the .so your library produces contain the symbol?

**Comment by leechor** [comment] 2021-03-13 03:56
> That's the nm output for the libjniX.so library, right? I'm more curious about the nm output for your library. The compiled code from the JavaCPP code generator will have a declared, undefined symbol for all of the used symbols from your library (U in nm's output) which will be resolved by the dynamic linker when ran. This is intended behaviour as we're linking multiple shared libraries together at runtime.
> 
> The undefined symbol error is reported by the dynamic linker because it failed to resolve where the symbol points to, which means it has no definition to link to. Does the .so your library produces contain the symbol?

It's double libjniX.so...
the origin libPubMethod.so `nm -D` output is:
`
0000000000011e3e T CAntennaModels::CalAntennaModel(std::basic_string<char, std::char_traits<char>, std::allocator<char> >, double, double, double, double, double, double, double*, std::basic_string<char, std::char_traits<char>, std::allocator<char> >&)
`

**Comment by saudet** [comment] 2021-03-13 09:17
It looks like your library was compiled with an old version of GCC. Make sure your annotations contain `@Platform(define = "_GLIBCXX_USE_CXX11_ABI 0", ...`, see https://stackoverflow.com/questions/33394934/converting-std-cxx11string-to-stdstring among other places for some explanations.

**Comment by leechor** [comment] 2021-03-13 09:32
> It looks like your library was compiled with an old version of GCC. Make sure your annotations contain `@Platform(define = "_GLIBCXX_USE_CXX11_ABI 0", ...`, see https://stackoverflow.com/questions/33394934/converting-std-cxx11string-to-stdstring among other places for some explanations.

It works, thank you~~

**Closed** 2021-03-13 09:48 UTC
