### ISSUE TITLE
Bindings for Qt?

### ISSUE THREAD

**Issue by oscarvarto** [bytedeco/javacpp#210] opened 2017-12-01 22:51 UTC
Hi!

I wonder if someone has tried to use javacpp to generate Qt bindings. Is it possible?
Qt is very mature and has a lot of functionality.

**Comment by saudet** [comment] 2017-12-02 02:00
Sure, it's possible, contributions are welcome :) If you'd like to give it a try, but are having any issues, please let me know.

**Comment by saudet** [comment] 2019-01-21 02:51
Duplicate of https://github.com/bytedeco/javacpp-presets/pull/674

Thanks to @freastro for starting work on this!

**Closed by saudet** 2019-01-21 02:51 UTC
Labels: enhancement
