### ISSUE TITLE
> **_**Some problems were encountered while building the effective model for **org.bytedeco:helloworld:jar:1.0-1.5.1-SNAPSHOT**_****

### ISSUE THREAD

**Issue by suguna-mother** [bytedeco/javacpp#326] opened 2019-08-13 05:57 UTC
> **_**Some problems were encountered while building the effective model for **org.bytedeco:helloworld:jar:1.0-1.5.1-SNAPSHOT**_****
> 'version' contains an expression but should be a constant. @ org.bytedeco:helloworld:${revision}, C:\Users\admin\Documents\NetBeansProjects\HelloWorldTest\javacpp-presets-helloworld\helloworld\pom.xml, line 14, column 14
> 
> It is highly recommended to fix these problems because they threaten the stability of your build.
> 
> For this reason, future Maven versions might no longer support building such malformed projects.
> 
> Inspecting build with total of 1 modules...
> Installing Nexus Staging features:
> ... total of 1 executions of maven-deploy-plugin replaced with nexus-staging-maven-plugin
> 
> Building JavaCPP Presets for helloworld 1.0-1.5.1-SNAPSHOT****

@saudet,  I've copied it from existing pom.xml files (I think I copied from cpython/pom.xml), let me know if there is anything else to fix.

I'm creating a new PR with the latest version of helloworld (2.0) with an example of a struct.
Sorry for the delay on my replies!

_Originally posted by @matteodg in https://github.com/bytedeco/javacpp/issues/323#issuecomment-520693239_

**Comment by suguna-mother** [comment] 2019-08-13 06:04
@matteodg  i have done helloworld in ubuntu, **saudet** where helped me to execute.
And if u done the helloworld in windows just tell me the steps to solve.

**Comment by suguna-mother** [comment] 2019-08-13 06:06
and i'm trying to execute an pylon in ubuntu.
**but it shows an error like:**
**Failed to execute goal on project pylon-platform: Could not resolve dependencies for project
org.bytedeco:pylon-platform:jar:5.0.5-1.3.3-SNAPSHOT: The following artifacts could not be resolved:
org.bytedeco:Pylon:jar:5.0.5-1.3.3-SNAPSHOT, org.bytedeco:Pylon:jar:linux-x86_64:5.0.5-1.3.3-
SNAPSHOT: Could not find artifact org.bytedeco:Pylon:jar:5.0.5-1.3.3-SNAPSHOT -> [Help 1]**

**Comment by saudet** [comment] 2019-08-14 12:17
Try again with helloworld 2.0. The presets have been updated.

**Comment by saudet** [comment] 2019-08-14 12:18
Duplicate of #323

**Closed by saudet** 2019-08-14 12:18 UTC
Labels: bug, duplicate
