### ISSUE TITLE
Is it possible to use JNA's callback?

### ISSUE THREAD

**Issue by oneengineer** [bytedeco/javacpp#416] opened 2020-07-25 06:54 UTC
It seems self defined callback fuctions in JAVACPP always require a C compiler.
However it is not very handy especially when people do not need the high performance.
JNA seems provide a way to write callback function in pure JAVA.

It is possbile to somehow let JAVACPP use the callback function created by JNA?
For example, conver the callback object in JNA to a Pointer in JAVACPP

**Comment by saudet** [comment] 2020-07-25 08:24
JNA uses [libffi](https://sourceware.org/libffi/) to do that, so we could do the same with JavaCPP.
It would be pretty easy to create presets for libffi's very simple API:
http://www.chiark.greenend.org.uk/doc/libffi-dev/html/Using-libffi.html
Someone needs to do it though, but if you would like to give it a try, contributions are welcome!

**Comment by saudet** [comment] 2020-07-25 08:28
It's also possible to use JNA with JavaCPP, and it usually works as expected, for example:
https://github.com/bytedeco/javacpp-presets/blob/master/llvm/samples/polly/MatMulBenchmark.java

**Comment by saudet** [comment] 2020-07-25 08:29
Duplicate of https://github.com/bytedeco/javacpp-presets/issues/833

**Closed by saudet** 2020-07-25 08:29 UTC
Labels: duplicate, question
