### ISSUE TITLE
Exception in thread "main" java.lang.NoClassDefFoundError: org/bytedeco/javacpp/avutil$AVFrame.

### ISSUE THREAD

**Issue by balajikaliappan** [bytedeco/javacpp#10] opened 2015-02-14 02:29 UTC
Hi,
I'm trying to capture the png image from mp4 video Using ffmpegframegrabber and it works fine in Mac os buy not in Linux server. I'm getting this error when I try to execute the code in the Linux server. please help

Thanks,
Balaji

**Comment by saudet** [comment] 2015-04-04 01:05
Sorry for the late reply. I've just noticed that I had not answered this question. If you're using an old version of glibc, you might need to rebuild the native artifacts on your version of Linux. Marking as duplicate of this: https://github.com/bytedeco/javacpp-presets/issues/22

**Closed by saudet** 2015-04-04 01:05 UTC
Labels: duplicate
