### ISSUE TITLE
How does one encode a series of images into H264.

### ISSUE THREAD

**Issue by nguyenquocchinhdev** [bytedeco/javacpp#208] opened 2017-11-21 09:08 UTC
hi guy,

How does one encode a series of images into H264? 
Can anybody please help me to solve the issue?

Thaks.

**Comment by saudet** [comment] 2017-11-21 11:36
Duplicate of https://github.com/bytedeco/javacv/issues/834

**Closed** 2017-11-21 11:36 UTC
Labels: duplicate, question
