### ISSUE TITLE
JavaFXFrameConverter.java:[47,12] cannot find symbol   symbol:   class Image

### ISSUE THREAD

**Issue by machh** [bytedeco/javacpp#709] opened 2023-09-13 13:24 UTC
my  env:

aarch :  aarch64

os  :  centos-7.9

gcc : 4.8.5  

When I  compilation and installation of the javacv project on a CentOS system running on an aarch64 platform, I execute the following command:

`
mvn clean install
`

Then, the following error print occurred .

`
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /home/javacv-1.5.3/src/main/java/org/bytedeco/javacv/JavaFXFrameConverter.java:[27,26] package javafx.scene.image does not exist
[ERROR] /home/javacv-1.5.3/src/main/java/org/bytedeco/javacv/JavaFXFrameConverter.java:[28,26] package javafx.scene.image does not exist
[ERROR] /home/javacv-1.5.3/src/main/java/org/bytedeco/javacv/JavaFXFrameConverter.java:[29,26] package javafx.scene.image does not exist
[ERROR] /home/javacv-1.5.3/src/main/java/org/bytedeco/javacv/JavaFXFrameConverter.java:[30,26] package javafx.scene.image does not exist
[ERROR] /home/javacv-1.5.3/src/main/java/org/bytedeco/javacv/JavaFXFrameConverter.java:[31,26] package javafx.scene.image does not exist
[ERROR] /home/javacv-1.5.3/src/main/java/org/bytedeco/javacv/JavaFXFrameConverter.java:[32,26] package javafx.scene.paint does not exist
[ERROR] /home/javacv-1.5.3/src/main/java/org/bytedeco/javacv/JavaFXFrameConverter.java:[39,58] cannot find symbol
  symbol: class Image
[ERROR] /home/javacv-1.5.3/src/main/java/org/bytedeco/javacv/JavaFXFrameConverter.java:[42,26] cannot find symbol
  symbol:   class Image
  location: class org.bytedeco.javacv.JavaFXFrameConverter
[ERROR] /home/javacv-1.5.3/src/main/java/org/bytedeco/javacv/JavaFXFrameConverter.java:[47,12] cannot find symbol
  symbol:   class Image
  location: class org.bytedeco.javacv.JavaFXFrameConverter
[ERROR] /home/javacv-1.5.3/src/main/java/org/bytedeco/javacv/JavaFXFrameConverter.java:[55,39] cannot find symbol
  symbol:   class PixelReader
  location: class org.bytedeco.javacv.JavaFXFrameConverter
[ERROR] /home/javacv-1.5.3/src/main/java/org/bytedeco/javacv/JavaFXFrameConverter.java:[64,16] cannot find symbol
  symbol:   class PixelFormat
  location: class org.bytedeco.javacv.JavaFXFrameConverter.FramePixelReader
[ERROR] /home/javacv-1.5.3/src/main/java/org/bytedeco/javacv/JavaFXFrameConverter.java:[74,16] cannot find symbol
  symbol:   class Color
  location: class org.bytedeco.javacv.JavaFXFrameConverter.FramePixelReader
[ERROR] /home/javacv-1.5.3/src/main/java/org/bytedeco/javacv/JavaFXFrameConverter.java:[79,78] cannot find symbol
  symbol:   class WritablePixelFormat
  location: class org.bytedeco.javacv.JavaFXFrameConverter.FramePixelReader
[ERROR] /home/javacv-1.5.3/src/main/java/org/bytedeco/javacv/JavaFXFrameConverter.java:[101,59] cannot find symbol
  symbol:   class WritablePixelFormat
  location: class org.bytedeco.javacv.JavaFXFrameConverter.FramePixelReader
[ERROR] /home/javacv-1.5.3/src/main/java/org/bytedeco/javacv/JavaFXFrameConverter.java:[106,59] cannot find symbol
  symbol:   class WritablePixelFormat
  location: class org.bytedeco.javacv.JavaFXFrameConverter.FramePixelReader
[ERROR] /home/javacv-1.5.3/src/main/java/org/bytedeco/javacv/JavaFXFrameConverter.java:[50,9] cannot find symbol
  symbol:   class PixelReader
  location: class org.bytedeco.javacv.JavaFXFrameConverter
[ERROR] /home/javacv-1.5.3/src/main/java/org/bytedeco/javacv/JavaFXFrameConverter.java:[51,9] cannot find symbol
  symbol:   class WritableImage
  location: class org.bytedeco.javacv.JavaFXFrameConverter
[ERROR] /home/javacv-1.5.3/src/main/java/org/bytedeco/javacv/JavaFXFrameConverter.java:[51,36] cannot find symbol
  symbol:   class WritableImage
  location: class org.bytedeco.javacv.JavaFXFrameConverter
[ERROR] /home/javacv-1.5.3/src/main/java/org/bytedeco/javacv/JavaFXFrameConverter.java:[63,9] method does not override or implement a method from a supertype
[ERROR] /home/javacv-1.5.3/src/main/java/org/bytedeco/javacv/JavaFXFrameConverter.java:[68,9] method does not override or implement a method from a supertype
[ERROR] /home/javacv-1.5.3/src/main/java/org/bytedeco/javacv/JavaFXFrameConverter.java:[73,9] method does not override or implement a method from a supertype
[ERROR] /home/javacv-1.5.3/src/main/java/org/bytedeco/javacv/JavaFXFrameConverter.java:[78,9] method does not override or implement a method from a supertype
[ERROR] /home/javacv-1.5.3/src/main/java/org/bytedeco/javacv/JavaFXFrameConverter.java:[100,9] method does not override or implement a method from a supertype
[ERROR] /home/javacv-1.5.3/src/main/java/org/bytedeco/javacv/JavaFXFrameConverter.java:[105,9] method does not override or implement a method from a supertype
[INFO] 24 errors
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
`

**Comment by saudet** [comment] 2023-09-21 06:07
If you don't need that class you can simply delete that file.

**Comment by saudet** [comment] 2023-10-04 23:22
Duplicate of https://github.com/bytedeco/javacv/issues/2101

**Closed by saudet** 2023-10-04 23:22 UTC
Labels: question
