### ISSUE TITLE
Force usage of GetPrimitiveArrayCritical instead of GetIntArrayElement

### ISSUE THREAD

**Issue by vincent-grosbois** [bytedeco/javacpp#253] opened 2018-08-23 09:05 UTC
Hello!
when using java-cpp with MKL, I noticed that for methods that do matrix / vector multiplication, array copies will occur.
For instance a MKL method take a _int*_ will be correctly transformed by java-cpp to a method that takes a _int[]_ instance, however the generate cpp code calls _GetIntArrayElements_ / _ReleaseIntArrayElements_ which makes a copy of the underlying data. As we usually want to use MKL on JVM for perf reason, this extra copy is enough to remove the advantage of using the MKL all-together.
Looking at the source code, I see that we will call the _critical_ JNI methods (that don't do copies) under some circonstances:
`if (methodInfo.valueGetter || methodInfo.valueSetter ||
                            methodInfo.memberGetter || methodInfo.memberSetter) `

So I have a few questions:
 - why is it that in that use case we want to use the critical version of array reads? why is it not always the case ?
 - would it be possible to add an extra config option so that we use the critical version all the time? If so, should this flag be in the _methodInfo_ instance or somewhere else (ie a global config) ? I can do the PR if needed but I'm not sure how it should be done.

Thanks !

**Comment by saudet** [comment] 2018-08-23 10:15
Yes, it would be possible. Marking this as duplicate of issue #16, contributions welcome!

**Closed by saudet** 2018-08-23 10:15 UTC
Labels: duplicate, enhancement
