### ISSUE TITLE
how to choose os classifier when maven building

### ISSUE THREAD

**Issue by winhkey** [bytedeco/javacpp#662] opened 2023-03-22 11:23 UTC
I have used os-maven-plugin to select ${os.detected.classifier} for other dependency, but it is different with javacpp, for example: osx-x86_64 vs. macosx-x86_64
<build>
        <extensions>
            <extension>
                <groupId>kr.motd.maven</groupId>
                <artifactId>os-maven-plugin</artifactId>
                <version>1.7.0</version>
            </extension>
        </extensions>
</build>

**Comment by winhkey** [comment] 2023-03-23 02:13
> You mean something like `mvn install -Djavacpp.platform=macosx-x86_64`?
> 
> If you have an actual question, you'll need to ask it to get an answer.

OK, I will change the question.
In my common module, if all the os classifiers have been dependent on, how to exclude unwanted
in the actual project module dependenting the common module?

**Comment by winhkey** [comment] 2023-03-23 02:35
say a digression, it would be great if everyone configure the same ${os.detected.classifier}.

**Comment by saudet** [comment] 2023-03-23 02:57
You mean something like this?
https://github.com/bytedeco/javacpp-presets/wiki/Reducing-the-Number-of-Dependencies

**Comment by saudet** [comment] 2023-03-24 11:07
Duplicate of https://github.com/bytedeco/javacpp-presets/issues/846

**Closed by saudet** 2023-03-24 11:07 UTC
Labels: duplicate, enhancement, question

**Comment by saudet** [comment] 2023-03-24 13:57
@winhkey I think this might answer your question: 
https://github.com/bytedeco/javacpp-presets/issues/846#issuecomment-1482762303

**Comment by winhkey** [comment] 2023-04-11 12:53
> @winhkey I think this might answer your question: [bytedeco/javacpp-presets#846 (comment)](https://github.com/bytedeco/javacpp-presets/issues/846#issuecomment-1482762303)

OK, it looks good, thank you very much~
