### ISSUE TITLE
Pointer.physicalBytes() on Mac should use phys_footprint not resident_size?

### ISSUE THREAD

**Issue by balgillo** [bytedeco/javacpp#516] opened 2021-09-28 12:47 UTC
[The implementation of Pointer.physicalBytes()](https://github.com/bytedeco/javacpp/blob/2b27e3f291735a297d37fda7959bf6894f5b2cef/src/main/java/org/bytedeco/javacpp/tools/Generator.java#L545) is platform-specific, and on Mac it reads `resident_size` returned by the `TASK_BASIC_INFO` call to the kernel (via `task_info`).

This matches `ps` RSS readings but is different from `top` output.  More worryingly, we've seen much higher values reported e.g. 3 GB from `ps`, 750 MB from `top` for the same process on an M1 Mac.  The high value of `resident_size` results in JavaCPP failing to allocate native memory with `OutOfMemoryError` because it thinks that there is too much native memory in use by the process already.

I found a [post from Apple guru "Eskimo"](https://developer.apple.com/forums/thread/105088#357415022) which says:

> The concept of footprint was introduced as an abstract representation of the general memory impact of a process, with the intention to isolate higher-level software from the gory details.... If you’re going to record a single number, this footprint value is a good one to use.... it’s much more useful value than all the older stuff (like resident_size)

So, should JavaCPP be changed to read the footprint size instead of the RSS when running on the Mac platform?

In practice, this would involve changing the `physicalBytes()` method to request `TASK_VM_INFO` and reading the `phys_footprint` value returned instead of `resident_size`.  The idea is from the [same page](https://developer.apple.com/forums/thread/105088) with Eskimo's comment.

In the meantime, we are working around this by setting Java property `org.bytedeco.javacpp.maxPhysicalBytes=0` as suggested in 
https://github.com/bytedeco/javacpp/issues/468.

**Comment by saudet** [comment] 2021-09-28 13:23
That sounds like a good number to use on Mac, but I'm not sure how we'd go about getting the equivalent of that on Linux and Windows. Do you happen to know the definition of "physical footprint"? Also, on Windows, getting a better estimate involves a lot of processing, so I'm not sure it's worth the extra cycles spent on that. As imperfect as it may be, the "resident/working set" is at least a pretty well defined number across platform. Trying to use random numbers on different platforms is bound to cause problems.

BTW, do you happen to know to what extent  ZGC affects the estimates reported by `phys_footprint`? I get 0 hits on Google about that... Anyway, let's continue the discussion at issue #468. Thanks!

**Comment by saudet** [comment] 2021-09-28 13:23
Duplicate of #468

**Closed by saudet** 2021-09-28 13:23 UTC
Labels: duplicate, enhancement

**Comment by saudet** [comment] 2021-09-28 13:28
BTW, if you would like to have JavaCPP generate different code depending on whether a specific macro is defined or not, that's very easy to do. Please open a pull request with what you'd like to have JavaCPP generate as custom code, such as the one, for example, for NO_WINDOWS_H that allows users to skip that part of the code:
https://github.com/bytedeco/javacpp/blob/master/src/main/java/org/bytedeco/javacpp/tools/Generator.java#L341
