### ISSUE TITLE
Some problems about using javacpp in AndroidStdio

### ISSUE THREAD

**Issue by ggNirvana** [bytedeco/javacpp#320] opened 2019-07-26 02:56 UTC

**Comment by ggNirvana** [comment] 2019-07-26 03:06
I am trying to using javacpp in as . I created Config.java like this.

import org.bytedeco.javacpp.annotation.Platform;
import org.bytedeco.javacpp.annotation.Properties;
import org.bytedeco.javacpp.tools.InfoMap;
import org.bytedeco.javacpp.tools.InfoMapper;

@Properties(
        value = @Platform(
                includepath = {"E:\\complex-c++selfMultiH\\app\\src\\main\\java\\idl\\baidu\\cpp\\Camera.h",
                        "E:\\complex-c++selfMultiH\\app\\src\\main\\java\\idl\\baidu\\cpp\\Server.h"},
                include = {"E:\\complex-c++selfMultiH\\app\\src\\main\\java\\idl\\baidu\\cpp\\Camera.h",
                        "E:\\complex-c++selfMultiH\\app\\src\\main\\java\\idl\\baidu\\cpp\\Server.h"}
        ),
        target = "NativeLibrary"
)
public class NativeLibraryConfig implements InfoMapper {
    public void map(InfoMap infoMap) {
    }

}


And I ran 
"javac -cp javacpp.jar Confg.java  
“java -jar..."

And it created NativeLibrary.java successfully. It extends my Config.java.
If I try to run javacpp again to get jni files , I will get NativeLibrary.java again. Could you tell me how to solve this?

**Comment by ggNirvana** [comment] 2019-07-26 03:07
I am using gradle to get jni files 


android.applicationVariants.all { variant ->
    def projectDir = project.projectDir.absolutePath
    def classesDir = variant.javaCompile.destinationDir
    def jniDir = file("$projectDir/src/main/cpp/").absolutePath
    variant.javaCompile.doLast {
        println '===javacpp start==='
        javaexec {
            main = 'org.bytedeco.javacpp.tools.Builder'
            classpath = files(configurations.javacpp.asPath)
            args '-cp', "$classesDir",
                    '-properties', 'android-arm',
                    '-Dplatform.root=' + ndkPath,
                    '-Dplatform.compiler=' + ndkPath + '/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-g++',
                    "-nocompile", "idl.baidu.cpp.*",
                    "-d", "${jniDir}" // jni file destination folder.
        }
        println '===javacpp done==='
    }
}

**Comment by saudet** [comment] 2019-07-26 03:29
You'll to run JavaCPP on NativeLibrary, not NativeLibraryConfig.

**Comment by ggNirvana** [comment] 2019-07-26 03:32
So it happens because there is someting wrong  with my gradle?

**Comment by saudet** [comment] 2019-07-26 05:47
To use it in Gradle, you'll need to have it execute the 4 commands here:
https://github.com/bytedeco/javacpp/wiki/Mapping-Recipes#introduction

**Comment by saudet** [comment] 2019-07-26 05:48
Duplicate of #65

**Closed by saudet** 2019-07-26 05:48 UTC
Labels: duplicate, enhancement, question

**Comment by ggNirvana** [comment] 2019-07-26 05:51
ok , thanks for your help!

**Comment by saudet** [comment] 2020-05-21 00:41
BTW, a build plugin for Gradle is now available here:
https://github.com/bytedeco/gradle-javacpp
If you try it out and find anything missing, please let me know!
