### ISSUE TITLE
Why i am getting this error?

### ISSUE THREAD

**Issue by ananth10** [bytedeco/javacpp#165] opened 2017-02-08 12:47 UTC
record (org.bytedeco.javacv.Frame) in FFmpegFrameRecorder cannot be applied to

(org.bytedeco.javacpp.opencv_core.IplImage)

**Comment by saudet** [comment] 2017-02-08 13:46
Duplicate of https://github.com/bytedeco/javacv/issues/619

**Closed by saudet** 2017-02-08 13:46 UTC
Labels: duplicate, question
