### ISSUE TITLE
Separate the Maven plugin from the core library for OSGi

### ISSUE THREAD

**Issue by timothyjward** [bytedeco/javacpp#327] opened 2019-08-14 09:47 UTC
JavaCPP provides a runtime library and Maven plugin all rolled into one. This is a poor separation of concerns, and leads to Maven dependencies getting pulled in at runtime. The Maven plugin should be built and published as a separate module.

**Comment by saudet** [comment] 2019-08-14 09:54
What's the issue?

**Comment by timothyjward** [comment] 2019-08-14 09:57
If, for example, I want to use JavaCPP as a JPMS module or an OSGi bundle then I need to satisfy all of the dependencies of JavaCPP. This includes a large amount of the Maven runtime that is needed to satisfy the dependencies of the Mojos included in the main jar file, even though it is highly unlikely that anyone is using the Mojo outside of a Maven build.

**Comment by timothyjward** [comment] 2019-08-14 09:58
I'm happy to put together a PR demonstrating how the project could be better separated so that it was easier to consume.

**Comment by saudet** [comment] 2019-08-14 09:59
The dependencies are marked "optional". That's a feature of Maven missing from JPMS, but Maven plugins don't support JPMS anyway, so there is no issue.

Creating more modules wouldn't make it easier to consume. It would just confuse users about which modules they need.

**Comment by timothyjward** [comment] 2019-08-14 10:01
> Creating more modules wouldn't make it easier to consume. It would just confuse users about which modules they need.

This is simply not true. At the moment it is not possible to consume this library in OSGi without repackaging it in a complicated and error prone way while *hoping* that users don't try to access the Mojos, or by providing the whole of Maven. Marking a dependency "optional" in Maven does't remove the dependency, it just makes parts of it break at runtime.

**Comment by timothyjward** [comment] 2019-08-14 10:03
> Creating more modules wouldn't make it easier to consume. It would just confuse users about which modules they need.

Also, looking back at the issues for this repository shows that people have had problems with the current setup. At the moment the project is having to work around the fact that it is a maven plugin, but that you want to publish it as a jar file. It is confusing for Maven users to have all of this in one place.

**Comment by saudet** [comment] 2019-08-14 10:17
I don't know of anyone else this has confused but you. If we need to change the way things are just for OSGi though, let's keep this issue opened and see how many people need this, or if someone can figure out a nice way to make this work, like we were able to do for JPMS.

**Comment by timothyjward** [comment] 2019-08-14 10:26
> If we need to change the way things are just for OSGi though, let's keep this issue opened and see how many people need this, or if someone can figure out a nice way to make this work, like we were able to do for JPMS.

JPMS also needs this if it's going to work correctly (as does plain Java really). The module-info.java as written does not declare the Maven dependencies, so if anyone tries to use the `BuildMojo` or `ParserMojo` then the application will go bang. The same is true in Java if you don't have the Maven Jars on the class path.

**Comment by saudet** [comment] 2019-08-14 10:35
No one has ever tried to do that. It's not a concern.

**Comment by saudet** [comment] 2019-08-14 11:19
Duplicate of #328

**Closed by saudet** 2019-08-14 11:19 UTC
Labels: duplicate, enhancement
