### ISSUE TITLE
can we use main class in javacpp to execute the program

### ISSUE THREAD

**Issue by suguna-mother** [bytedeco/javacpp#330] opened 2019-08-19 05:45 UTC

**Comment by suguna-mother** [comment] 2019-08-19 05:49
i know that java connectivity based on c/c++ native library,But i have some doubt for main class that may be have some issue while calling main class

**Comment by saudet** [comment] 2019-08-19 06:39
Are you getting any error messages? Could you explain what you're trying to do?

**Comment by suguna-mother** [comment] 2019-08-19 06:57
Has based on pylon program i have created an main class and from that formation i have been calling some native funtion in main class.
in that format i get some exceptions error just already commented in comment#323

**Comment by suguna-mother** [comment] 2019-08-19 06:59
i just have doubt in javacpp, if that main class can be executable?

**Comment by saudet** [comment] 2019-08-19 07:50
If you're trying to use something @jpsacha did, you'll need to ask him about that.

**Comment by saudet** [comment] 2019-08-21 04:55
Duplicate of https://github.com/bytedeco/javacv-examples/issues/21

**Closed by saudet** 2019-08-21 04:55 UTC
Labels: duplicate, question
