### ISSUE TITLE
Question: regarding library loader

### ISSUE THREAD

**Issue by netbrain** [bytedeco/javacpp#291] opened 2019-03-13 09:41 UTC
So I have created a library that has dependencies on opencv and built it with javacpp.

```
  $ objdump ...

  NEEDED               libopencv_stitching.so.4.0
  NEEDED               libopencv_aruco.so.4.0
  NEEDED               libopencv_bgsegm.so.4.0
  NEEDED               libopencv_bioinspired.so.4.0
  NEEDED               libopencv_face.so.4.0
  NEEDED               libopencv_img_hash.so.4.0
  NEEDED               libopencv_saliency.so.4.0
  NEEDED               libopencv_structured_light.so.4.0
  NEEDED               libopencv_superres.so.4.0
  NEEDED               libopencv_text.so.4.0
  NEEDED               libopencv_tracking.so.4.0
  NEEDED               libopencv_videostab.so.4.0
  NEEDED               libopencv_xfeatures2d.so.4.0
  NEEDED               libopencv_xphoto.so.4.0
  NEEDED               libopencv_shape.so.4.0
  NEEDED               libopencv_objdetect.so.4.0
  NEEDED               libopencv_phase_unwrapping.so.4.0
  NEEDED               libopencv_optflow.so.4.0
  NEEDED               libopencv_ximgproc.so.4.0
  NEEDED               libopencv_ml.so.4.0
  NEEDED               libopencv_dnn.so.4.0
  NEEDED               libopencv_plot.so.4.0
  NEEDED               libopencv_video.so.4.0
  NEEDED               libopencv_calib3d.so.4.0
  NEEDED               libopencv_features2d.so.4.0
  NEEDED               libopencv_flann.so.4.0
  NEEDED               libopencv_highgui.so.4.0
  NEEDED               libopencv_videoio.so.4.0
  NEEDED               libopencv_imgcodecs.so.4.0
  NEEDED               libopencv_photo.so.4.0
  NEEDED               libopencv_imgproc.so.4.0
  NEEDED               libopencv_core.so.4.0
```

However when using this library in the jvm complains that it cant find the   libopencv_stitching.so.4.0, and i guess it will try to find all the others aswell.

  libopencv_stitching.so.4.0 is however available in the javacpp-presets opencv module which i have on my classpath. I would presume that the Loader would be able to detect this, and load this for me? no?

So what is at fault here?

**Comment by saudet** [comment] 2019-03-13 10:16
If you're using the Maven plugin, you'll need to add it to its dependencies
as well.

**Comment by netbrain** [comment] 2019-03-13 10:40
Right now the project uses the gradle plugin. Are you saying that the library i build has to add a dependency on opencv-4.0.1-1.4.4-linux-x86.jar and have it set in a pom.xml file?

Is this due to loading order of jar files in the classpath? or does the loader read this information somehow?

**Comment by saudet** [comment] 2019-03-13 11:21
Gradle plugin? JavaCPP doesn't have a Gradle plugin...

**Comment by netbrain** [comment] 2019-03-13 11:25
No sorry, i meant i'm building my project using gradle.

**Comment by saudet** [comment] 2019-03-13 11:29
Ah, ok, so add `opencv-platform` as dependency as shown in the README.md file and you're good to go.

**Comment by saudet** [comment] 2019-03-13 11:36
If `MSSSaliency` is a native class, we'll need to build for C++. The closest example that does this with Gradle is this one from Chip Kent @illumon-public: https://github.com/illumon-public/JavaCppGradleTemplate
If you need help with that template, ask here and let's see if Chip Kent replies...

Other than that, we'd need to have a plugin for Gradle, so I'll just mark this as duplicate of issue #65.

**Closed by saudet** 2019-03-13 11:36 UTC
Labels: duplicate, enhancement, question

**Comment by netbrain** [comment] 2019-03-13 11:52
@saudet The gradle project i have now is working in terms of compiling the source code in c++ into shared library files. This is then packaged into a jar file which is incldued in another java project.

However im struggling with this: `caused by: java.lang.UnsatisfiedLinkError: /home/netbrain/.javacpp/cache/mss-saliency-1.0.0-1.9.9.jar/org/fjank/msssaliency/linux-x86_64/libjni_mss-saliency_100.so: libopencv_stitching.so.4.0: cannot open shared object file: No such file or directory`

However libopencv_stitching is available on the classpath. so why does it fail to load it?

**Comment by netbrain** [comment] 2019-03-13 11:56
Can i somehow declare a dependency on `opencv-4.0.1-1.4.4-linux-x86.jar` which currently holds the sought after library files? so that when the jvm tries to load libjni_mss-saliency_100.so it will first load all required native files within `opencv-4.0.1-1.4.4-linux-x86.jar`?

I've tried the "preload" statement in the class mapping but to no avail.

**Comment by saudet** [comment] 2019-03-13 12:41
For starters, you'll need to add `@Properties(inherit = opencv_stitching.class, ...)` as is done for Chilitags, flandmark, Caffe, and MXNet.

**Comment by saudet** [comment] 2019-03-14 01:00
We can also do without inheriting platform properties, but then you'd need basically copy the properties from OpenCV that are listed in `presets/opencv_core.java`, `presets/opencv_imgproc.java`, etc. In particular, since there is a version number attached to the SONAME, we need to include it in the platform properties as well so this means, for example, `link = {"opencv_core@.4.0", "opencv_imgproc@.4.0", ...}`, not just "opencv_core" or "opencv_imgproc" like you have right now. Since there is no file named "libopencv_core.so", etc in the JAR files, it will obviously not be able to extract it! JAR files do not support symbolic links: https://bugs.openjdk.java.net/browse/JDK-6550137

**Comment by saudet** [comment] 2019-03-17 23:53
If you're still having issues getting this to work, make sure to set the "org.bytedeco.javacpp.logger.debug" system property to "true" and see what it's trying to do.

**Comment by netbrain** [comment] 2019-03-19 10:42
@saudet thanks for the tip. I managed to get it to build using the link attribute.

**Comment by saudet** [comment] 2020-05-21 00:40
BTW, a build plugin for Gradle is now available here:
https://github.com/bytedeco/gradle-javacpp
If you try it out and find anything missing, please let me know!
