### ISSUE TITLE
Generating endian-aware field accessors for structs

### ISSUE THREAD

**Issue by jverne** [bytedeco/javacpp#200] opened 2017-09-06 16:05 UTC
We've inherited a native library that is expected to run on any number of architectures, and I'm currently trying to generate some JNI code that will be deployed in an embedded environment. There is no parser preset for this library (i.e., I did not create one, and the library provider gave us an annotated Java class that we use as a basis for everything javacpp generates).

We have noticed an issue when compiling for big-endian architectures (e.g., 32-bit MIPS eb) where a struct that is used to "portably" hold some wide Unicode char values needs to be byte-swapped. That is, if we hack the generated CPP file to swap the results of field data we get the correct Unicode data. On little-endian architectures we don't have to hack the generated struct field accessors.

Note:
- We can't _really_ modify these struct defs. Whether or not this is the right way to manipulate wide chars is beside the point, because this is the legacy cross-platform code that we have, all driven with lots of defines.
- I'd rather not go down the path of setting up a preset. While it would be nice to have a parser generate all the boilerplate, because this is embedded development I cannot count on maven or even bash being available. We'd have to turn our build system inside out, and it's already brittle enough! I'm ok with patching a "NativeAPI" Java class as input to  `org.bytedeco.javacpp.tools.Builder` to generate what we need for our targets.
- Another group has described to me the problem and their hack solution. Because of the embedded nature of the work, I'm having trouble actually duplicating their results because of incomplete runtime emulation (e.g., deploying code to, and seeing the results on, a big-endian MIPS device). I'm working on this, but I think the following code describes the problem sufficiently.

Here's the header file that describes an example struct. (This is an example. We have several of these structs, and in some cases a struct like this one is included in another struct.):

```
/** Legacy code. Shows how the sizes of the structs are calculated for reference. **/
#define CM_BUFFERLENGTH(_type, _num)  \
   (sizeof(_type) * (_num + 1))

typedef unsigned short CM_UINT16;
typedef CM_UINT16 CM_WCHAR;

/* UNICODE data */
typedef struct {
    CM_WCHAR name[CM_BUFFERLENGTH(CM_WCHAR, 256)];
    CM_WCHAR fnord[CM_BUFFERLENGTH(CM_WCHAR, 256)];
} FnordStruct;
```
Here's the Java static class that we use to describe the Java side of this struct:

  ```
  @Name("FnordStruct")
    public static class FnordStruct extends Pointer {
        static {
            Loader.load();
        }

        public FnordStruct() { allocate(); }
        private native void allocate();

        /** name field **/
        private native @Cast("CM_WCHAR") char name(int i);
        @MemberGetter private native @Cast("CM_WCHAR*") CharPointer name();
        private native FnordStruct name(int i, char s);

        public String getName() {
            return name().getString();
        }

        public FnordStruct setName(String string) {
            for (int counter = 0; counter < string.length(); counter++) {
                name(counter, string.charAt(counter));
            }
            name(string.length(), '\0');
            return this;
        }

        /** fnord field **/
        private native @Cast("CM_WCHAR") char fnord(int i);
        @MemberGetter private native @Cast("CM_WCHAR*") CharPointer fnord();
        private native FnordStruct fnord(int i, char s);

        public String getFnord() {
            return fnord().getString();
        }
        public FnordStruct setFnord(String string) {
            for (int counter = 0; counter < string.length(); counter++) {
                fnord(counter, string.charAt(counter));
            }
            fnord(string.length(), '\0');
            return this;
        }
    }
```
Here's a snippet from the generated `fnordjni.cpp` file:

```
JNIEXPORT jchar JNICALL Java_org_clvrmnky_FnordAPI_00024FnordStruct_fnord__I(JNIEnv* env, jobject obj, jint arg0) {
    ::FnordStruct* ptr = (::FnordStruct*)jlong_to_ptr(env->GetLongField(obj, JavaCPP_addressFID));
    if (ptr == NULL) {
        env->ThrowNew(JavaCPP_getClass(env, 17), "This pointer address is NULL.");
        return 0;
    }
    jlong position = env->GetLongField(obj, JavaCPP_positionFID);
    ptr += position;
    jchar rarg = 0;
    CM_WCHAR rvalue = (CM_WCHAR)ptr->fnord[arg0];
    rarg = (jchar)rvalue;
    return rarg;
}
```
On big-endian machines, we are finding that we have to do something like this after fetching the rvalue from the field:
```
swap(&rvalue, &rvalue, 2);
```
`swap` is a function that knows how to swap unsigned short values found in the arrays passed in. This is, of course, an egregious hack.

Is there a way to annotate the Java class so that we use Pointer, or CharPointer in a more portable manner, and one that does not require hacking the generated CPP? I can't quite grok the examples provided. I was also unable to find exactly what I was looking for in the presets, though I admit I did not read them all.

**Comment by jverne** [comment] 2017-09-06 21:13
Well, I cloned javacpp-presets and did a search for "endian" and got lots of hits.

Any specific advice is still welcome while I dig into that.

**Comment by saudet** [comment] 2017-09-06 22:02
The Pointer classes were not designed to deal with endianness, for now
anyway. We can use NIO buffers for that though. Would there be anything
missing from using those?

**Comment by jverne** [comment] 2017-09-07 14:01
Aha, I suppose that makes sense. Do you mean use `java.nio.Buffer` and friends directly, or through an appropriate `org.bytedeco.javacpp.Indexer`? Any example code somewhere, perhaps in the presets? I guess I can search in the preset project for uses of `Indexer` and/or `UShortArrayIndexer`.

**Comment by saudet** [comment] 2017-09-07 20:20
Yes, by using buffers directly, but buffers don't support custom types, say an array of structs, so I'm wondering if this is the kind of issue you're having?

**Comment by jverne** [comment] 2017-09-07 21:36
The report is that when reading or writing these struct fields, which are arrays of (essentially) unsigned shorts, the resulting values are not in the expected order. The assumption is that each value is a pair of octets that represent some Unicode value. On big-endian architectures we have to swap each octet to get valid Unicode into those strings.

i.e., when we do something like `CM_WCHAR rvalue = (CM_WCHAR)ptr->fnord[arg0]` to get the whole field, rvalue seems to be an array of little-endian 16-bit values.

Now, I'm confused that the setters also require this, as I assumed that the Java side is big-endian already, but the `Java_org_clvrmnky_FnordAPI_00024FnordStruct_fnord__IC()` function has to be augmented by hand so that we do the same thing on before doing `ptr->fnord[arg0] = (NQ_WCHAR)arg1`. So, I'm puzzled how a String to jchar used as an right-hand value for setting a struct field isn't just working (or, alternatively, fails on a little-endian architecture if it is architecture sensitive.

However, at the end of the day, I'm trying to figure out how to make sure these byte-swappable values are read or written the right way for the arch.

**Comment by saudet** [comment] 2017-09-07 21:55
Ok, so if we're only looking into arrays of 16-bit numbers, then NIO buffers are great for that. Calling `CharPointer.limit(256).asBuffer()` will get you a `CharBuffer`, but the endianness will already be set, so we can call `.limit(256).asByteBuffer().order(ByteOrder.BIG_ENDIAN).asCharBuffer()` and that will do what you need, I believe.

**Comment by jverne** [comment] 2017-10-10 14:01
I'll swing back and tell my tale if this works. I'm in the process of tweaking all my accessors now, and have a working MIPS env again.

**Comment by jverne** [comment] 2017-10-11 19:00
I'm going to continue this thread from a new comment for clarity. This is more of a snaity check because every time I have to look at NIO for anything other than Files I get confused.

Assume I have a struct with a field `name` that I want setters and getters for. I think I need to do something like this:

       private native @Cast("CM_WCHAR") char name(int i);
       @MemberGetter private native @Cast("CM_WCHAR*") CharPointer name();   
       private native FnordStruct name(int i, char s);

       public String getName() {
        	return name().limit(someValue).asByteBuffer().order(myByteOrder).asCharBuffer().toString();
        }

        public FnordStruct setName(String string) {
        	// Get a ByteBuffer that will do the conversion for us.
        	ByteBuffer buf = ByteBuffer.allocate(4).order(ENDIAN);

        	int index = 0;
        	for (char c : string.toCharArray()) {
        		buf.clear();
        		buf.putChar(c);
        		buf.flip();
        		name(index, buf.getChar());
        		index++;
        	}
        	name(string.length(), '\0');

            return this;
        }

That is, we need to set the limit so the ByteBuffer we get covers the entire range of of the CharPointer. But for the setter we just need to encode each char as we go, a char at a time. Did I miss anything, or grossly misunderstand the solution?

**Comment by saudet** [comment] 2017-10-13 01:43
The `CharBuffer` that we get shares the same memory space as the original `CharPointer`, so we can simply call `CharBuffer.put(String)` on it and that should be it.

**Comment by saudet** [comment] 2021-12-03 00:27
Now that Panama FMA seems pretty advanced, it would make sense to add support for it for this use case as well.

/cc @HGuillemet @eix128 @mcimadamore @LifeIsStrange

**Comment by saudet** [comment] 2021-12-03 00:28
Duplicate of #402

**Closed by saudet** 2021-12-03 00:28 UTC
Labels: duplicate, enhancement
