### ISSUE TITLE
How should std::wstring& type be converted

### ISSUE THREAD

**Issue by ACCia** [bytedeco/javacpp#334] opened 2019-08-21 09:41 UTC
I have added the @Cast("std::wstring&") annotation, but there is no correct output after the call.

My native code
`void WinToastTemplate::setFirstLine(_In_ const std::wstring& ws) `

java code

`public native void setFirstLine(@Const @Cast("std::wstring&") BytePointer text);`

**Comment by saudet** [comment] 2019-08-21 10:04
We can use `@StdWString` for that with `CharPointer` on Windows.

**Comment by saudet** [comment] 2019-08-21 10:05
Duplicate of #261

**Closed by saudet** 2019-08-21 10:05 UTC
Labels: duplicate, question
