### ISSUE TITLE
Support for Java 11

### ISSUE THREAD

**Issue by nirupamarachuri** [bytedeco/javacpp#267] opened 2018-10-08 21:57 UTC
Is there any version of javacpp that supports Java 11? If not, when is it planned to release?

**Comment by saudet** [comment] 2018-10-08 22:28
It should work just fine, what error are you getting?

**Comment by nirupamarachuri** [comment] 2018-10-09 00:12
Using javacpp v1.3.3. On running the jdeps scan the error received is:

javacpp-1.3.3.jar -> jdk.unsupported org.bytedeco.javacpp.indexer.UnsafeRaw -> sun.misc.Unsafe JDK internal API (jdk.unsupported) JDK Internal API Suggested Replacement ---------------- --------------------- sun.misc.Unsafe See http://openjdk.java.net/jeps/260

What version is compatible with Java 11?

**Comment by saudet** [comment] 2018-10-09 00:16
There are still no alternatives to sun.misc.Unsafe in Java 11, so that's alright. It's only a warning.

**Comment by saudet** [comment] 2018-10-09 00:37
I've just tested Oracle JDK 11 for Linux under Fedora 27 and everything seems to be working well. The unit tests for JavaCPP and JavaCV all pass, and buildings the presets for OpenCV from scratch also works fine. The only thing that JavaCPP doesn't support yet are modules, so I'll mark this as a duplicate of #252.

**Closed by saudet** 2018-10-09 00:37 UTC
Labels: duplicate, enhancement
