### ISSUE TITLE
writing my presets,how to write my InfoMap?

### ISSUE THREAD

**Issue by wpzybyq** [bytedeco/javacpp#412] opened 2020-07-13 09:41 UTC
my .h file like this:class ClassA: public std::unordered_multimap<std::string,ClassB *, StructA, StructB>,how to write my InfoMap?
i add Info Like this: infoMap.put(new Info("std::unordered_multimap<std::string,ClassB *, StructA, StructB>").pointerTypes("String").define());,but get error info:std::unordered_multimap<std::string,ClassB*,StructA,StructB>.java:[18,127] <identifier> expected

**Comment by saudet** [comment] 2020-07-13 12:02
Please start by reading this page: https://github.com/bytedeco/javacpp/wiki/Mapping-Recipes

**Comment by saudet** [comment] 2020-07-14 03:00
Duplicate of https://github.com/bytedeco/javacpp-presets/issues/905

**Closed by saudet** 2020-07-14 03:00 UTC
Labels: duplicate
